import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const galleryURL = new URL('./desktop-v3-artifact-gallery.tsx', import.meta.url)

test('artifact gallery is a live collection review surface distinct from plan execution', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /data-artifact-review-surface/)
  assert.match(gallery, /data-artifact-collection-sidebar/)
  assert.match(gallery, /data-artifact-studio-step-sidebar/)
  assert.match(gallery, /aria-label="Artifact Studio steps"/)
  assert.match(gallery, /data-artifact-studio-unified-iterations/)
  assert.match(gallery, /data-artifact-studio-turns/)
  assert.match(gallery, /aria-label="Artifact turn progression"/)
  assert.match(gallery, /selectedTurns\.map\(\(turn\) =>/)
  assert.match(gallery, /Every AI creation round is one turn/)
  assert.match(gallery, /data-artifact-studio-turn-part/)
  assert.match(gallery, /selectPartIterationArtifact\(artifact, turnPart\.partId\)/)
  assert.doesNotMatch(gallery, /data-artifact-studio-part-iterations/)
  assert.match(gallery, /studioModeActive && !previewFullscreen \? <aside/)
  assert.match(gallery, /studioSectionId \|\| selectedTurns\.length/)
  assert.match(gallery, /setSelectedPartIds\(targetPartId && selected && desktopV3ArtifactRevisionHasPart\(selected, targetPartId\) \? \[targetPartId\] : \[\]\)/)
  assert.match(gallery, /requestedPartId \|\| studioSectionLineage\?\.iterationSectionId/)
  assert.match(gallery, /iterationAutoplayArtifactRef\.current === selectedKey && iterationAutoplaySectionRef\.current/)
  assert.doesNotMatch(gallery, /data-artifact-studio-full-iterations/)
  assert.doesNotMatch(gallery, /data-artifact-studio-revision-round/)
  assert.doesNotMatch(gallery, /data-mobile-revision-turn-selector/)
  assert.doesNotMatch(gallery, /data-desktop-revision-turn-selector/)
  assert.doesNotMatch(gallery, /aria-label="Select artifact revision turn"/)
  assert.match(gallery, /!studioModeActive && selectedRounds\.length > 1[\s\S]*selectedRounds\.map\(\(round\) =>/)
  assert.match(gallery, /selectedRound\?\.candidates \?\? selectedGroup\?\.entries/)
  assert.match(gallery, /selectFullIterationArtifact\(artifact\)/)
  assert.match(gallery, /data-artifact-studio-branch/)
  assert.doesNotMatch(gallery, /data-artifact-player-iteration-chooser/)
  assert.match(gallery, /selectStudioArtifact\(artifact, section\)/)
  assert.match(gallery, /selectArtifact\(artifact\)/)
  assert.doesNotMatch(gallery, /selectStudioArtifact[\s\S]{0,500}selectArtifact\(artifact, false\)/)
  assert.match(gallery, /iterationAutoplayArtifactRef\.current = artifactKey/)
  assert.match(gallery, /iterationAutoplaySectionRef\.current = targetSectionId/)
  assert.match(gallery, /artifactSelectionKey\(selected\) === artifactKey[\s\S]*startIterationSectionPlayback\(targetSection, true\)/)
  assert.match(gallery, /startIterationSectionPlayback\(section, true\)/)
  assert.match(gallery, /setIterationPlayerReadyVersion\(\(current\) => current \+ 1\)/)
  assert.match(gallery, /iterationSeekAcknowledgerRef\.current\?\.reset\(\)[\s\S]*sendAnimationMessage\('stop'\)[\s\S]*iterationDescribeArtifactRef\.current = artifactKey[\s\S]*iterationDescribeRequestRef\.current = sendAnimationMessage\('describe'\)/)
  assert.match(gallery, /iterationPlayerArtifactRef\.current = describedArtifactKey/)
  assert.match(gallery, /requestIterationDescription\(artifactSelectionKey\(selected\)\)/)
  assert.match(gallery, /resolveDesktopV3ArtifactAutoplaySection/)
  assert.match(gallery, /artifactSelectionKey\(selected\)/)
  assert.match(gallery, /iterationPlayerArtifactRef\.current/)
  assert.match(gallery, /alternatives\.map\(\(artifact, alternativeIndex\) => renderStudioBranch\(artifact, alternativeIndex, section\)\)/)
  assert.match(gallery, /!studioModeActive/)
  assert.match(gallery, /desktopV3ArtifactStudioSectionAlternatives/)
  assert.doesNotMatch(gallery, /desktopV3ArtifactStudioBranchDepth/)
  assert.match(gallery, /const iterationRoundSourceArtifact = activeIterationAlternative/)
  assert.match(gallery, /desktopV3ArtifactStudioParent\(artifacts, activeIterationAlternative\)/)
  assert.match(gallery, /setStudioActiveBranchId\(artifactKey\)/)
  assert.match(gallery, /onActiveBranchChange/)
  assert.match(gallery, /data-artifact-next-section/)
  assert.match(gallery, /desktopV3ArtifactIterationNextSectionDescription/)
  assert.doesNotMatch(gallery, /data-artifact-lock-section/)
  assert.doesNotMatch(gallery, /Locked branch/)
  assert.match(gallery, /const studioSectionId = iterationSection\?\.id \?\? studioSectionLineage\?\.iterationSectionId/)
  assert.match(gallery, /iterationPlayerReadyVersion === 0[\s\S]*const targetSectionId = studioSectionLineage\?\.iterationSectionId \?\? ''[\s\S]*initialPlaybackArtifactRef\.current === selectedKey[\s\S]*initialPlaybackArtifactRef\.current = selectedKey[\s\S]*setSelectedPartIds\(\[targetSection\.id\]\)[\s\S]*startIterationSectionPlayback\(targetSection, true\)/)
  assert.match(gallery, /initialPartPlaybackRef\.current !== requestKey[\s\S]*selectedArtifactKeyRef\.current === artifactKey[\s\S]*descriptor\.sections\.find[\s\S]*startIterationSectionPlayback\(targetSection, true\)/)
  assert.match(gallery, /selectPartIterationArtifact[\s\S]*artifactSelectionKey\(selected\) === artifactKey[\s\S]*startIterationSectionPlayback\(targetSection, true\)/)
  assert.match(gallery, /overflow-x-hidden md:pl-72 xl:pl-80/)
  assert.match(gallery, /w-72 overflow-x-hidden overflow-y-auto/)
  assert.match(gallery, /xl:w-80 md:block/)
  assert.match(gallery, /select its iteration here\. The preview starts at that step/)
  assert.match(gallery, /aria-label=\{`\$\{section\.label\} branches`\}/)
  assert.match(gallery, /grid-cols-1 gap-2 pb-2 sm:grid-cols-2 md:hidden/)
  assert.match(gallery, /grid-cols-\[auto_minmax\(0,1fr\)_auto\]/)
  assert.match(gallery, /data-artifact-primary-playback/)
  assert.match(gallery, /Play animation/)
  assert.match(gallery, /Play from here/)
  assert.match(gallery, /aria-label="Whole artifact timeline"/)
  assert.match(gallery, /syncIterationSectionToTime\(nextMs\)/)
  assert.match(gallery, /DesktopV3ArtifactSeekAcknowledger/)
  assert.match(gallery, /iterationSeekAcknowledgerRef/)
  assert.match(gallery, /iterationSeekAcknowledgerRef\.current\?\.acknowledge\(data\.id\)/)
  assert.match(gallery, /iterationSeekAcknowledgerRef\.current\?\.setOnSettled/)
  assert.match(gallery, /iterationPlaybackStartedAtRef\.current = performance\.now\(\)/)
  assert.match(gallery, /seekIteration\(startMs\)/)
  assert.match(gallery, /data-artifact-parts/)
  assert.match(gallery, /data-artifact-ask-selected-parts/)
  assert.match(gallery, /selectedPartIds\.includes\(part\.id\)/)
  assert.match(gallery, /requestedParts\.map\(\(part\) =\u003e/)
  assert.match(gallery, /desktopV3ArtifactPartMessageSelection\(source, part\.id, 'use'\)/)
  assert.match(gallery, /selectedAcceptedPartCount/)
  assert.match(gallery, /Accepted revision/)
  assert.match(gallery, /Locked pending revision/)
  assert.match(gallery, /Ask changes to/)
  assert.match(gallery, /selectDesktopV3ArtifactPartRevisions\(source, choices\)/)
  assert.match(gallery, /data-artifact-staged-part-choices/)
  assert.match(gallery, /stagedPartChoices\[turnPart\.partId\]/)
  assert.match(gallery, /stagePartChoice\(artifact, turnPart\.partId, true\)/)
  assert.match(gallery, /data-artifact-apply-part-choices/)
  assert.match(gallery, /data-artifact-iterate-part/)
  assert.match(gallery, /desktopV3ArtifactPartIterationMessageSelection\(source, partId, 3\)/)
  assert.match(gallery, /Iterate again/)
  assert.match(gallery, /artifact\.status === 'failed' \|\| artifact\.status === 'unavailable' \? 'Failed'/)
  assert.match(gallery, /Stage lock/)
  assert.match(gallery, /Stage unlocked/)
  assert.match(gallery, /Apply atomically/)
  assert.match(gallery, /await onSelectionPersisted\?\.\(\)/)
  assert.match(gallery, /await refreshOpenDesktopV3ArtifactCatalogs\(\)/)
  assert.match(gallery, /Refresh completed; stage your choices again against the current composition/)
  assert.match(gallery, /startMs: locator\.startMs, endMs: iterationDescriptor\.durationMs/)
  assert.match(gallery, /selected\?\.partGraphState === 'git_projection'/)
  assert.match(gallery, /selected\?\.partGraphState === 'legacy_unproven'/)
  assert.doesNotMatch(gallery, /selected\.parts\.map/)
  assert.doesNotMatch(gallery, /data-artifact-section-alternatives/)
  assert.match(gallery, /break-words text-\[11px\]/)
  assert.match(gallery, /Live collections/)
  assert.match(gallery, /Collection progress/)
  assert.match(gallery, /generating/)
  assert.match(gallery, /failed/)
  assert.match(gallery, /Search collections, variants, sessions, or types/)
  assert.match(gallery, /aria-label="Previous artifact"/)
  assert.match(gallery, /aria-label="Next artifact"/)
  assert.doesNotMatch(gallery, /!studioModeActive \? <>\s*<button[^>]*aria-label="Previous artifact"/)
  assert.match(gallery, /iterationGroupId/)
  assert.match(gallery, /iterationDisplayLabel/)
  assert.match(gallery, /Open iteration URL/)
  assert.match(gallery, /onArtifactNavigate/)
  assert.match(gallery, /onClick=\{\(event\) => openArtifactLink\(event, artifact\)\}/)
  assert.match(gallery, /onClick=\{\(event\) => openArtifactLink\(event, selected\)\}/)
  assert.match(gallery, /onClick=\{\(event\) => openCollectionLink\(event, group\)\}/)
  assert.match(gallery, /event\.preventDefault\(\)/)
  assert.match(gallery, /data-artifact-collection-overview/)
  assert.match(gallery, /data-artifact-download-collection/)
  assert.match(gallery, /fetchDesktopV3ArtifactCollectionBundle\(artifact\.sessionId, artifact\.collectionId\)/)
  assert.match(gallery, /Download all ready/)
  assert.match(gallery, /overviewGroup\.entries\.some\(\(artifact\) => artifactCanReveal\(artifact\) && Boolean\(artifact\.collectionId\)\)/)
  assert.match(gallery, /artifactCanReveal\(selected\)/)
  assert.match(gallery, /artifact\.status !== 'staging'/)
  assert.match(gallery, /artifact\.content === undefined/)
  assert.match(gallery, /setActionConfirmation\(`Opened \$\{result\.displayLocation\}`\)/)
  assert.match(gallery, /Could not open this artifact in the native file manager/)
  assert.match(gallery, /desktopV3ArtifactRequiresBundle\(selected\) \? 'Download bundle' : 'Download file'/)
  assert.match(gallery, /const overviewGroup = groups\.find/)
  assert.match(gallery, /setOverviewCollectionKey\(group\.key\)/)
  assert.match(gallery, /artifactLabel !== collectionLabel/)
  assert.match(gallery, /selected\.description !== selected\.collectionDescription/)
  assert.match(gallery, /const owningSessionId = artifact\.lineage\?\.parentSessionId \|\| artifact\.sessionId/)
  assert.doesNotMatch(gallery, /if \(!open \|\| !selected\) return undefined\s+setSelectedId\(artifactSelectionKey\(selected\)\)/)
  assert.doesNotMatch(gallery, /DesktopPlanExecutionSidebar/)
})

test('gallery chat actions emit opaque references and persist use before callback', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /export interface DesktopV3ArtifactChatSelection/)
  assert.match(gallery, /selection: DesktopV3ArtifactSelection/)
  assert.match(gallery, /onAddToChat\(pendingChatArtifacts\.map\(\(artifact\) => \{/)
  assert.match(gallery, /selection = desktopV3ArtifactMessageSelection\(artifact, 'select'\)/)
  assert.match(gallery, /description: messageSelection\.description/)
  assert.match(gallery, /canonicalSelection = await useDesktopV3Artifact\(desktopV3ArtifactSelection\(selected\)\)/)
  assert.match(gallery, /messageSelection = desktopV3ArtifactMessageSelection\(selected, 'use'\)/)
  assert.match(gallery, /description: messageSelection\.description, selection: canonicalSelection/)
  assert.match(gallery, /data-artifact-selected-design/)
  assert.match(gallery, /Attach.*for changes<\/span>/)
  assert.match(gallery, /Attach for changes keeps the durable selected design unchanged/)
  assert.match(gallery, /Use this design & continue/)
  assert.match(gallery, /desktopV3ArtifactMessageSelection\(artifact, 'use'\)/)
  assert.match(gallery, /Active complete artifact branch for section/)
  assert.doesNotMatch(gallery, /arrayBuffer\(\)/)
  assert.doesNotMatch(gallery, /onAddToChat\(\{[^}]*content:/)
  assert.doesNotMatch(gallery, /arrayBuffer\(\).*onAddToChat/)
})

test('gallery exposes the exact-reference HTML-to-video-stills bridge without browser capture or render authority', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /data-artifact-export-video-stills/)
  assert.match(gallery, /Video stills/)
  assert.match(gallery, /desktopV3ArtifactCanExportHTMLStills\(selected\)/)
  assert.match(gallery, /desktopV3ArtifactSelection\(selected\)/)
  assert.match(gallery, /DESKTOP_V3_HTML_STILL_EXPORT_PROMPT/)
  assert.match(gallery, /refreshOpenDesktopV3ArtifactCatalogs\(\)/)
  assert.match(gallery, /The managed PNGs will appear here when ready/)
  assert.match(gallery, /setActionPending\('export-video-stills'\)/)
  assert.match(gallery, /setActionError\(error instanceof Error \? error\.message : 'Could not request video-ready still export'\)/)
  assert.doesNotMatch(gallery, /html2canvas/)
  assert.doesNotMatch(gallery, /drawImage\(.*iframe/)
  assert.doesNotMatch(gallery, /accept.*proposal/i)
  assert.doesNotMatch(gallery, /start.*render/i)
})

test('mobile gallery reserves a stable middle generation viewport between selectors and actions', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /data-mobile-artifact-three-zone-layout/)
  assert.match(gallery, /grid-rows-\[auto_minmax\(0,1fr\)_auto\]/)
  assert.match(gallery, /data-mobile-generation-selector/)
  assert.match(gallery, /aria-label="Select generation"/)
  assert.match(gallery, /data-mobile-generation-actions/)
  assert.match(gallery, /h-\[100dvh\]/)
  assert.match(gallery, /safe-area-inset-bottom/)
  assert.doesNotMatch(gallery, /h-\[100dvh\] w-\[100dvw\].*data-artifact-review-surface/)
})

test('open catalog consumes realtime refresh demand and keeps previews sandboxed', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /useDesktopV3OpenArtifactCatalogRefresh\(open, refreshCatalog\)/)
  assert.match(gallery, /const catalog = await fetchDesktopV3ArtifactCatalogResult\(\)/)
  assert.match(gallery, /setArtifacts\(catalog\.artifacts\)/)
  assert.match(gallery, /sandbox="allow-scripts"/)
  assert.match(gallery, /sandbox=""/)
  assert.match(gallery, /referrerPolicy="no-referrer"/)
  assert.match(gallery, /selected\.mediaType\.startsWith\('image\/'\).*previewURL/)
  assert.match(gallery, /<img[^>]*src=\{previewURL\}/)
  assert.match(gallery, /fetchDesktopV3ArtifactPreviewAccess/)
  assert.match(gallery, /preflightDesktopV3ArtifactDirectContent/)
  assert.doesNotMatch(gallery, /srcDoc=/)
  assert.doesNotMatch(gallery, /setPreviewURL\(URL\.createObjectURL\(/)
  assert.match(gallery, /data-artifact-video-player/)
  assert.match(gallery, /<video[^>]*src=\{previewURL\} controls/)
  assert.doesNotMatch(gallery, /selected\.mediaType === 'image\/svg\+xml'.*no inline preview/)
  assert.doesNotMatch(gallery, /allow-same-origin/)
})
