import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

const paneURL = new URL('./desktop-v3-new-session-pane.tsx', import.meta.url)
const composerURL = new URL('./desktop-v3-agentic-composer.tsx', import.meta.url)

test('new Desktop chat uses only the routed controller and endpoint before activation', async () => {
  const source = await readFile(paneURL, 'utf8')

  assert.match(source, /new DesktopV3RoutedNewSessionController\(async \(request\)/)
  assert.doesNotMatch(source, /routedController\.startDraft\(\)/)
  assert.match(source, /initialControllerState\.phase === 'failed'/)
  assert.match(source, /postDesktopV3RoutedSessionStart\(request\)/)
  assert.match(source, /controller\.submit\(\{/)
  assert.match(source, /controller\.retry\(\)/)
  assert.match(source, /controller\.prepareOperationIdentity\(\)/)
  assert.match(source, /stageDesktopComposerAttachments\(\{/)
  assert.match(source, /routedClientRequestId: identity\.clientRequestId/)
  assert.match(source, /existing: history/)
  assert.match(source, /stagedHistory\.slice\(history\.length\)/)
  assert.match(source, /attachments: snapshot\.attachments/)
  assert.match(source, /snapshot\.attachments\.length > 0 \? 'Please review the attached file\(s\)\.'/)
  assert.match(source, /captured\.attachments\.length !== stagedAttachmentsRef\.current\.length/)
  assert.match(source, /setLocalError\(cause instanceof Error \? cause\.message : 'Routed session start failed\.'\)/)
  assert.match(source, /operationAttachmentsRef\.current = \[\.\.\.stagedAttachmentsRef\.current\]/)
  assert.match(source, /reconcileDesktopComposerStagedAttachments\(submittedAttachments, result\.first_message\)/)
  assert.match(source, /result\.first_message\.media\?\.length/)
  assert.match(source, /onRoutedSessionResolved: \(result: DesktopV3RoutedStartResult\)/)
  assert.match(source, /Promise\.resolve\(\)[\s\S]*resolvedCallbackRef\.current\(routedState\.result\)/)
  assert.match(source, /controller\.acknowledgeResolved\(operationId\)/)
  assert.match(source, /controller\.getState\(\)\.phase === 'resolved'[\s\S]*controller\.rejectResolved\(operationId, error\)/)

  assert.doesNotMatch(source, /\bcreateDesktopV3NewSessionOperation\b/)
  assert.doesNotMatch(source, /\bstartNewDesktopV3Session\b/)
  assert.doesNotMatch(source, /\bappendFirstDesktopV3Message\b/)
  assert.doesNotMatch(source, /modeCommand|pendingWorktreeBranch|initialMode|onModeChange|workspaceSlug|routeOptions|onOpenChats/)
  assert.doesNotMatch(source, /dispatchDesktopV3Cache|retainDesktopV3RealtimeController|bootstrapDesktopV3SidebarMetadataOnly/)
  assert.doesNotMatch(source, /useNavigate|navigate\(/)
})

test('routed pending and failure stay local and retry the persisted controller identity', async () => {
  const paneSource = await readFile(paneURL, 'utf8')
  const composerSource = await readFile(composerURL, 'utf8')

  assert.match(paneSource, /<DesktopV3RoutedPendingShell[\s\S]*state=\{pendingState\}[\s\S]*pendingPrompt=\{routedState\.prompt\}/)
  assert.match(paneSource, /routedState\.phase === 'failed'[\s\S]*controller\.retry\(\)/)
  assert.match(paneSource, /const visibleAttachments = restoredAttachments\.filter[\s\S]*visibleAttachments\.length !== current\.snapshot\.attachments\.length[\s\S]*controller\.retry\(\)/)
  assert.match(paneSource, /removedStagedAttachmentIdsRef\.current\.add\(stagingId\)/)
  assert.match(paneSource, /stagedAttachmentsRef\.current = visibleAttachments/)
  assert.match(paneSource, /setDraft\(routedState\.snapshot\.prompt\)/)
  assert.match(paneSource, /setWorktreeIntent\(createDesktopRoutedWorktreeIntent\(routedState\.snapshot\.worktreePrimed\)\)/)
  assert.match(paneSource, /setMode\(routedState\.snapshot\.planModeRequested \? 'plan' : 'auto'\)/)
  assert.match(paneSource, /setRestoredSnapshot\(routedState\.snapshot\)/)
  assert.match(paneSource, /routedState\.phase === 'draft'/)
  assert.match(paneSource, /createDesktopV3RoutedComposerSnapshot\(\{/)
  assert.match(composerSource, /attachments: desktopComposerStagedMediaInput\(routedStagedAttachments\)/)
  assert.match(composerSource, /selectedAction: selectedWorkspaceAction/)
  assert.match(composerSource, /selectedSkill: selectedWorkspaceSkill/)
  assert.match(composerSource, /worktreePrimed: routedWorktreeRequested/)
  assert.match(composerSource, /planModeRequested: mode === 'plan'/)
  assert.match(composerSource, /setSelectedWorkspaceAction\(\(routedComposerSnapshot\.selectedAction as WorkspaceAction \| null\) \?\? null\)/)
  assert.match(composerSource, /setSelectedWorkspaceSkill\(\(routedComposerSnapshot\.selectedSkill as WorkspaceSkill \| null\) \?\? null\)/)
  assert.match(composerSource, /routedTextFiles = files\.filter\(isComposerTextFile\)/)
  assert.match(composerSource, /routedMediaFiles = files\.filter\(\(file\) => !isComposerTextFile\(file\)\)/)
  assert.match(composerSource, /textAttachments\.reduce\([\s\S]*appendComposerTextFile\(nextDraft, attachment\.name, attachment\.fileType, attachment\.content\)/)
  assert.match(paneSource, /showComposer \? \([\s\S]*<DesktopV3AgenticComposer/)
  assert.match(paneSource, /routedNewSession/)
})

test('routed new-chat composer exposes explicit Worktree and Plan intent with a waiting model bar', async () => {
  const source = await readFile(composerURL, 'utf8')

  assert.match(source, /routedNewSession\?: boolean/)
  assert.match(source, /routedNewSession && showModePicker/)
  assert.match(source, /<DesktopComposerPlanToggle[\s\S]*active=\{mode === 'plan'\}[\s\S]*readOnly=\{mode === 'plan'\}/)
  assert.match(source, /resolvedSessionControls && showModePicker && mode === 'plan'/)
  assert.match(source, /onAttach=\{routedNewSession \? \(onRoutedStageAttachments/)
  assert.match(source, /<DesktopRoutedWorktreePrime requested=\{routedWorktreeRequested\}/)
  assert.match(source, /statusLabel=\{modelStatusLabel\}/)
  assert.doesNotMatch(source, /Attachments will be available after routed staging is connected/)
})
