export const desktopPlanSidebarVariant5 = {
  id: "variant-5",
  name: "Layered cards",
  description: "Polished card layout with elegant nesting, tactile shadows, and dedicated work panels for agent control.",
  classes: {
    sidebar: "flex flex-col h-full bg-[var(--app-surface-subtle)] border-l border-[var(--app-border)]",
    inner: "flex flex-col h-full p-4 gap-4",
    header: "flex items-center justify-between pb-3 border-b border-[var(--app-border)]",
    headerTitle: "text-xs font-bold uppercase tracking-wider text-[var(--app-text-muted)]",
    scrollRegion: "flex-1 overflow-y-auto space-y-4 pr-1 scrollbar-thin",
    checkpointSection: "bg-[var(--app-surface)] rounded-xl border border-[var(--app-border)] shadow-sm p-4 space-y-3 transition-all duration-200",
    checkpointLabel: "text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--app-text-subtle)]",
    status: "inline-flex items-center gap-1.5 px-2 py-0.5 rounded-full text-[10px] font-bold bg-[var(--app-surface-subtle)]",
    checkpointWrapper: "mt-1",
    checkpointTitle: "text-sm font-semibold text-[var(--app-text)] leading-snug break-words",
    checkpointId: "font-mono text-xs font-bold text-[var(--app-primary)] bg-[var(--app-primary-soft)] px-1.5 py-0.5 rounded mr-1.5",
    progress: "mt-2 bg-[var(--app-surface-subtle)] rounded-lg p-2.5 border border-[var(--app-border)]/50",
    progressMeta: "flex justify-between text-[10px] text-[var(--app-text-subtle)] mb-1 font-medium",
    progressTrack: "h-1.5 w-full bg-[var(--app-surface-subtle)] rounded-full overflow-hidden",
    progressFill: "h-full bg-[var(--app-primary)] rounded-full transition-all duration-300",
    nextUp: "mt-2 pt-2 border-t border-[var(--app-border)]/60 text-xs",
    nextCheckpoint: "mt-1.5 flex items-start gap-2 bg-[var(--app-surface-subtle)] p-2 rounded-lg border border-[var(--app-border)]/40 hover:border-[var(--app-border)] transition-colors",
    tasksSection: "bg-[var(--app-surface)] rounded-xl border border-[var(--app-border)] shadow-sm p-4 space-y-3",
    tasksHeading: "text-[10px] font-semibold uppercase tracking-[0.15em] text-[var(--app-text-subtle)]",
    taskRow: "flex items-start gap-2.5 text-xs text-[var(--app-text-muted)] py-1",
    taskDisclosure: "mt-2 pt-2 border-t border-[var(--app-border)]/40 w-full text-left",
    openPlanButton: "w-full h-8 flex items-center justify-center gap-1.5 text-xs font-medium rounded-lg border border-[var(--app-border)] bg-[var(--app-surface-subtle)] hover:bg-[var(--app-surface)] text-[var(--app-text)] transition-colors",
    actionsSection: "bg-[var(--app-surface)] rounded-xl border border-[var(--app-border)] shadow-sm p-4 space-y-3",
    subagents: {
      root: "w-full bg-[var(--app-surface)] rounded-xl border border-[var(--app-border)] shadow-sm overflow-hidden",
      summary: "flex items-center gap-2 px-3.5 py-3 cursor-pointer select-none text-xs font-medium text-[var(--app-text)] hover:bg-[var(--app-surface-subtle)] transition-colors focus-visible:outline-none",
      icon: "size-4 text-[var(--app-primary)] shrink-0",
      label: "font-semibold text-xs text-[var(--app-text)]",
      chevron: "size-4 text-[var(--app-text-subtle)] transition-transform duration-200 ml-auto",
      list: "px-3 pb-3 pt-1 space-y-2 border-t border-[var(--app-border)]/40 bg-[var(--app-surface-subtle)]",
      row: "group/row flex items-start gap-2 bg-[var(--app-surface)] rounded-lg border border-[var(--app-border)] shadow-xs p-2.5 hover:border-[var(--app-border)] focus-within:ring-1 focus-within:ring-[var(--app-primary)] transition-all",
      status: "size-2 mt-1.5 shrink-0 rounded-full",
      navigate: "flex-1 text-left min-w-0 focus:outline-none",
      title: "truncate text-xs font-semibold text-[var(--app-text)] leading-tight mb-0.5",
      meta: "flex items-center gap-1.5 text-[10px] text-[var(--app-text-subtle)]",
      progressTrack: "mt-1.5 h-1 w-full bg-[var(--app-surface-subtle)] rounded-full overflow-hidden",
      progressFill: "h-full bg-[var(--app-primary)] rounded-full transition-all duration-300",
      stop: "grid h-7 w-7 place-items-center rounded-md text-[var(--app-text-subtle)] hover:bg-[var(--app-danger-bg)] hover:text-[var(--app-danger)] focus:outline-none focus:ring-1 focus:ring-[var(--app-primary)] transition-colors shrink-0 self-center ml-1.5"
    }
  }
};
