import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const paneURL = new URL('./desktop-v3-existing-conversation-pane.tsx', import.meta.url)
const galleryURL = new URL('./desktop-v3-artifact-gallery.tsx', import.meta.url)
const thumbnailURL = new URL('./desktop-v3-artifact-preview-thumbnail.tsx', import.meta.url)
const apiURL = new URL('../../session-v3/artifact-api.ts', import.meta.url)

test('final handoff gallery uses authenticated opaque artifact routes and an isolated scripted HTML preview', async () => {
  const [pane, gallery, thumbnail, api] = await Promise.all([readFile(paneURL, 'utf8'), readFile(galleryURL, 'utf8'), readFile(thumbnailURL, 'utf8'), readFile(apiURL, 'utf8')])
  assert.match(pane, /handoffArtifacts\.length > 0/)
  assert.match(pane, /data-final-handoff-artifact-link/)
  assert.match(pane, /if \(!href\) return null/)
  assert.match(pane, /href=\{href\}/)
  assert.match(pane, /<DesktopV3ArtifactPreviewThumbnail artifact=\{artifact\}/)
  assert.match(pane, /handoffArtifacts\.length === 0 && \(\(recommendation\.prompt/)
  assert.doesNotMatch(pane, /<DesktopV3ArtifactGallery artifacts=\{handoffArtifacts\}/)
  assert.doesNotMatch(pane, /Open gallery/)
  assert.match(thumbnail, /fetchDesktopV3Artifact\(artifact\.sessionId, artifact\.artifactId/)
  assert.match(thumbnail, /artifact\.mediaType === 'text\/html'/)
  assert.match(thumbnail, /data-artifact-html-preview/)
  assert.match(thumbnail, /sandbox="allow-scripts"/)
  assert.match(thumbnail, /referrerPolicy="no-referrer"/)
  assert.match(gallery, /fetchDesktopV3Artifact\(selected\.sessionId, selected\.artifactId/)
  assert.match(gallery, /selected\.mediaType === 'text\/html'/)
  assert.match(gallery, /srcDoc=\{previewText\}/)
  assert.match(gallery, /sandbox="allow-scripts"/)
  assert.doesNotMatch(gallery, /sandbox="allow-same-origin allow-scripts"/)
  assert.match(gallery, /referrerPolicy="no-referrer"/)
  assert.match(gallery, /data-artifact-gallery-page/)
  assert.match(gallery, /fixed inset-0.*h-\[100dvh\].*w-\[100dvw\]/)
  assert.match(gallery, /Back to conversation/)
  assert.match(gallery, /aria-label="Previous artifact"/)
  assert.match(gallery, /aria-label="Next artifact"/)
  assert.doesNotMatch(gallery, /<Dialog role="dialog"[^>]*Final handoff artifacts/)
  assert.doesNotMatch(gallery, /data-artifact-gallery-fullscreen/)
  assert.doesNotMatch(gallery, /changedFiles.*DesktopV3ArtifactGallery/)
  assert.match(api, /apiFetch\(desktopV3ArtifactEndpoint/)
  assert.match(api, /fetchDesktopV3ArtifactBundle/)
  assert.match(api, /desktopV3ArtifactBundleEndpoint/)
  assert.match(api, /\/bundle`/)
  assert.match(gallery, /fetchDesktopV3ArtifactBundle\(artifact\.sessionId, artifact\.artifactId\)/)
  assert.match(gallery, /Download bundle/)
  assert.match(api, /encodeURIComponent\(normalizedArtifactId\)/)
  assert.match(gallery, /fetchDesktopV3ArtifactPreviewToken\(selected\.sessionId, selected\.artifactId/)
  assert.match(api, /buildDesktopV3ArtifactSandboxDocument/)
  assert.match(api, /connect-src 'none'/)
  assert.match(api, /desktopV3ArtifactPackageBaseEndpoint/)
  assert.match(api, /desktopV3ArtifactPackageEntryEndpoint/)
  assert.match(api, /__swarm_artifact_entry__\.html/)
  assert.match(api, /packageEntry = new URL\(desktopV3ArtifactPackageEntryEndpoint/)
  assert.match(api, /base\.href = packageEntry\.toString\(\)/)
  assert.match(api, /\/content\/access\/\$\{encodeURIComponent\(normalizedToken\)\}\//)
  assert.doesNotMatch(api, /artifact_preview=/)
})
