export const desktopPlanSidebarVariant6 = {
  id: "variant-6",
  name: "Minimal signal",
  description: "A low-chrome, typography-led treatment with precise separators, compact density, status as subtle signal, and a refined subagent disclosure.",
  classes: {
    sidebar: "h-full bg-[var(--app-surface)] flex flex-col font-sans text-[var(--app-text)] text-xs",
    inner: "flex flex-col flex-1 min-h-0 overflow-hidden gap-3 px-4 py-3",
    header: "border-b border-[var(--app-border)] pb-2 mb-1 flex items-center justify-between shrink-0",
    headerTitle: "text-xs font-semibold tracking-wider uppercase text-[var(--app-text-muted)]",
    scrollRegion: "flex-1 overflow-y-auto space-y-3.5 pr-0.5 [scrollbar-gutter:stable]",
    checkpointSection: "border-b border-[var(--app-border)] pb-3.5 space-y-2.5",
    checkpointLabel: "text-[9px] font-bold tracking-[0.2em] uppercase text-[var(--app-text-subtle)]",
    status: "text-[10px] font-mono font-medium tracking-wide uppercase px-1 py-0.5 rounded border border-current bg-transparent",
    checkpointWrapper: "mt-1",
    checkpointTitle: "text-xs font-semibold leading-relaxed text-[var(--app-text)]",
    checkpointId: "font-mono text-[10px] font-bold text-[var(--app-primary)] mr-1",
    progress: "space-y-1 mt-1",
    progressMeta: "flex justify-between text-[9px] tracking-wider text-[var(--app-text-subtle)]",
    progressTrack: "h-[2px] w-full bg-[var(--app-border)] rounded-full overflow-hidden",
    progressFill: "h-full bg-[var(--app-primary)] rounded-full",
    nextUp: "pt-2.5 space-y-1.5",
    nextCheckpoint: "pl-2.5 border-l border-[var(--app-border)] text-[11px] leading-relaxed",
    tasksSection: "border-t border-[var(--app-border)] pt-3.5 space-y-2",
    tasksHeading: "text-[9px] font-bold tracking-[0.2em] uppercase text-[var(--app-text-subtle)]",
    taskRow: "flex items-start gap-2.5 py-0.5 text-[11px] text-[var(--app-text-muted)] leading-relaxed",
    taskDisclosure: "flex items-center gap-1.5 py-1 text-[10px] text-[var(--app-text-subtle)] hover:text-[var(--app-text-muted)] transition-colors",
    openPlanButton: "w-full h-7 text-[10px] font-medium tracking-wider uppercase bg-transparent hover:bg-[var(--app-surface-subtle)] border border-[var(--app-border)] rounded text-[var(--app-text-muted)] transition-colors",
    actionsSection: "border-t border-[var(--app-border)] pt-3.5 space-y-2.5",
    subagents: {
      root: "group/subagents w-full overflow-hidden border-t border-b border-[var(--app-border)] py-1 bg-transparent",
      summary: "flex h-8 items-center justify-between cursor-pointer list-none text-[10px] font-semibold tracking-[0.15em] uppercase text-[var(--app-text-subtle)] hover:text-[var(--app-text-muted)] transition-colors select-none [&::-webkit-details-marker]:hidden",
      icon: "size-3 text-[var(--app-text-subtle)] mr-1.5 shrink-0",
      label: "flex items-center",
      chevron: "size-3.5 text-[var(--app-text-subtle)] transition-transform duration-200 group-open:rotate-90",
      list: "mt-1.5 grid gap-1 pr-0.5 max-h-48 overflow-y-auto",
      row: "grid grid-cols-[auto_1fr_auto] items-center gap-2 py-1 px-1.5 rounded hover:bg-[var(--app-surface-subtle)] transition-colors",
      status: "size-1.5 rounded-full",
      navigate: "min-w-0 text-left cursor-pointer select-none",
      title: "truncate text-[11px] font-medium text-[var(--app-text)] leading-none mb-0.5",
      meta: "flex items-center gap-1.5 text-[9px] text-[var(--app-text-subtle)] font-mono",
      progressTrack: "mt-1 h-[1px] bg-[var(--app-border)] w-full overflow-hidden",
      progressFill: "h-full bg-[var(--app-primary)]",
      stop: "grid h-6 w-6 place-items-center rounded text-[var(--app-text-subtle)] hover:bg-[var(--app-danger-bg)] hover:text-[var(--app-danger)] transition-colors"
    }
  }
};
