import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

test('Desktop V3 existing composer stages agent/model setup and persists profile settings through Agents API', async () => {
  const source = await readFile(new URL('./desktop-v3-existing-conversation-pane.tsx', import.meta.url), 'utf8')
  const composerSource = await readFile(new URL('./desktop-v3-agentic-composer.tsx', import.meta.url), 'utf8')
  const controlSource = await readFile(new URL('./agent-model-control.tsx', import.meta.url), 'utf8')

  assert.match(source, /useQuery\(agentStateQueryOptions\(\)\)/)
  assert.match(source, /resolveDesktopV3AgentModelLock\(agentState\.profiles/)
  assert.match(source, /rawCachedPreference\s*=\s*useDesktopV3CacheSelector\(\(state\)\s*=>\s*state\.preferencesBySession\[normalizedSessionId\]\)/)
  assert.match(source, /cachedPreference\s*=\s*useMemo\(\(\)\s*=>\s*normalizePreference\(rawCachedPreference\), \[rawCachedPreference\]\)/)
  assert.match(source, /function buildDesktopV3ExistingSettingsSnapshot\([\s\S]*metadataString\(input\.metadata, 'agent_name'\)[\s\S]*metadataString\(input\.metadata, 'resolved_agent_name'\)[\s\S]*policyString\(input\.agentModelPolicy, 'agentName', 'agent_name'\)/)
  assert.doesNotMatch(source, /fallbackAgent: agentState\.activePrimary/)
  assert.doesNotMatch(source, /fallbackAgent: string/)
  assert.match(source, /initializedSettingsSessionRef\.current !== normalizedSessionId/)
  assert.match(source, /await updateAgentProfile\(input\.profile, action\.agentPatch\)/)
  assert.match(source, /await refreshAgentModelMutationCaches\(queryClient\)/)
  const mutationSource = await readFile(new URL('../queries/agent-preference-mutations.ts', import.meta.url), 'utf8')
  assert.match(mutationSource, /const \[draftModelResult, agentStateResult, agentSettingsStateResult\] = await Promise\.all\(/)
  assert.match(mutationSource, /\.\.\.draftModelQueryOptions\(\),[\s\S]*staleTime: 0/)
  assert.match(mutationSource, /queryClient\.setQueryData\(draftModelQueryKey\(\), draftModelResult\)/)
  assert.match(mutationSource, /queryClient\.setQueryData\(agentStateQueryOptions\(\)\.queryKey, agentStateResult\)/)
  assert.match(mutationSource, /queryClient\.setQueryData\(agentSettingsStateQueryOptions\(\)\.queryKey, agentSettingsStateResult\)/)
  assert.match(source, /const nextAgentName = input\.agentName\.trim\(\)[\s\S]*if \(nextAgentName\)[\s\S]*await updateSessionV3Agent\(normalizedSessionId, nextAgentName\)/)
  assert.doesNotMatch(source, /action\.kind === 'default'[\s\S]*updateDraftModelPreference\(basePreference\)/)
  assert.match(source, /setSelectedAgent\(nextAgentName\)/)
  assert.doesNotMatch(source, /refreshedLock\.locked \|\| !preferencesEqual\(nextPreference, preference\)/)
  assert.match(source, /!refreshedLock\.locked \&\& !preferencesEqual\(nextPreference, preference\)/)
  assert.match(source, /await updateSessionV3Preference\(normalizedSessionId, \{[\s\S]*provider: nextPreference\.provider[\s\S]*contextMode: nextPreference\.contextMode/)
  assert.match(source, /displayedUsage = cachedUsageMatchesSelectedModel \&\& cachedUsageIsProviderSnapshot \? cachedUsage : null/)
  assert.match(source, /normalizeModelID\(cachedUsage\.provider, cachedUsage\.model\) === normalizeModelID\(selectedModelOption\.provider, selectedModelOption\.model\)/)
  assert.match(source, /effectiveContextWindowValue = selectedContextWindow > 0[\s\S]*\? selectedContextWindow/)
  assert.match(source, /formatDesktopV3ContextLabel\(effectiveContextWindowValue, displayedUsage\?\.remainingTokens\)/)
  assert.match(source, /handleModeSelect\(nextMode: DesktopSessionMode\)[\s\S]*modeMutationSequenceRef\.current = mutationSequence[\s\S]*localSettingsDirtyRef\.current\.mode = true[\s\S]*setMode\(nextMode\)[\s\S]*const nextLock = resolveDesktopV3AgentModelLock\(agentState\.profiles, selectedAgent, nextMode\)/)
  assert.doesNotMatch(source, /setMode\(nextMode\)\s*if \(!selectedAgentModelLock\.locked\) return\s*const nextLock = resolveDesktopV3AgentModelLock\(agentState\.profiles, selectedAgent, nextMode\)/)
  assert.match(source, /updateSessionV3Mode\(normalizedSessionId, nextMode\)[\s\S]*modeMutationSequenceRef\.current !== mutationSequence[\s\S]*sessionV3ModeSettingsMutationResponse\(\s*modeResponse,\s*normalizedSessionId,\s*nextMode/)
  assert.match(source, /dispatchDesktopV3Cache\(\{\s*type: "mutation\.sessionSettingsResult",\s*raw: settingsResponse/)
  assert.match(source, /\.catch\(\(error\) => \{[\s\S]*modeMutationSequenceRef\.current !== mutationSequence[\s\S]*setMode\(settingsBaseline\.mode\)[\s\S]*setSendError/)
  assert.match(source, /mode: normalizeSessionMode\(input\.cacheSession\?\.mode \|\| input\.session\?\.mode\)/)
  assert.doesNotMatch(source, /mode: normalizeSessionMode\(input\.session\?\.mode \|\| input\.cacheSession\?\.mode\)/)
  assert.match(source, /const cachedPolicyMatchesSelectedMode = mode === settingsBaseline\.mode/)
  assert.match(source, /if \(cachedPolicyMatchesSelectedMode && lockedPolicyPreference\)/)
  assert.match(source, /refreshAgentModelMutationCaches/)
  assert.doesNotMatch(source, /switchAgentToSingleModel/)
  assert.doesNotMatch(source, /switchAgentToDefaultModel/)

  assert.match(composerSource, /<button type="button" onClick=\{handleModeToggle\}[\s\S]*\{mode\}[\s\S]*<AgentModelControl/)
  assert.match(composerSource, /<AgentModelControl[\s\S]*triggerDetail=\{modelControlDetail/)
  assert.match(composerSource, /<AgentModelControl[\s\S]*onConfirmAgentSettings=\{onConfirmAgentSettings\}/)
  assert.doesNotMatch(composerSource, /<ModelPicker/)
  assert.doesNotMatch(composerSource, /<ThinkingPicker/)
  assert.doesNotMatch(composerSource, /onModelSelect/)
  assert.doesNotMatch(composerSource, /onThinkingChange/)
  assert.doesNotMatch(composerSource, /onFastChange/)

  assert.match(controlSource, /setDraftAgentName\(profile\.name\)/)
  assert.match(controlSource, /await onConfirmAgentSettings\?\.\(\{ agentName: profile\.name, profile, action \}\)/)
  assert.doesNotMatch(controlSource, /defaultPreference/)
  assert.doesNotMatch(controlSource, /onAgentSelect\(profile\.name\)/)
})
