import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'
import test from 'node:test'

const galleryURL = new URL('./desktop-v3-artifact-gallery.tsx', import.meta.url)

test('artifact gallery is a live collection review surface distinct from plan execution', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /data-artifact-review-surface/)
  assert.match(gallery, /data-artifact-collection-sidebar/)
  assert.match(gallery, /Live collections/)
  assert.match(gallery, /Collection progress/)
  assert.match(gallery, /generating/)
  assert.match(gallery, /failed/)
  assert.match(gallery, /Search collections, variants, sessions, or types/)
  assert.match(gallery, /aria-label="Previous artifact"/)
  assert.match(gallery, /aria-label="Next artifact"/)
  assert.match(gallery, /iterationGroupId/)
  assert.match(gallery, /iterationDisplayLabel/)
  assert.match(gallery, /Open iteration URL/)
  assert.match(gallery, /onArtifactNavigate/)
  assert.match(gallery, /onClick=\{\(event\) => openArtifactLink\(event, artifact\)\}/)
  assert.match(gallery, /onClick=\{\(event\) => openArtifactLink\(event, selected\)\}/)
  assert.match(gallery, /onClick=\{\(event\) => openCollectionLink\(event, group\)\}/)
  assert.match(gallery, /event\.preventDefault\(\)/)
  assert.match(gallery, /data-artifact-collection-overview/)
  assert.match(gallery, /data-artifact-download-collection/)
  assert.match(gallery, /fetchDesktopV3ArtifactCollectionBundle\(artifact\.sessionId, artifact\.collectionId\)/)
  assert.match(gallery, /Download all ready/)
  assert.match(gallery, /overviewGroup\.entries\.some\(\(artifact\) => artifactCanReveal\(artifact\) && Boolean\(artifact\.collectionId\)\)/)
  assert.match(gallery, /artifactCanReveal\(selected\)/)
  assert.match(gallery, /artifact\.status !== 'staging'/)
  assert.match(gallery, /artifact\.content === undefined/)
  assert.match(gallery, /setActionConfirmation\(`Opened \$\{result\.displayLocation\}`\)/)
  assert.match(gallery, /Could not open this artifact in the native file manager/)
  assert.match(gallery, /desktopV3ArtifactRequiresBundle\(selected\) \? 'Download bundle' : 'Download file'/)
  assert.match(gallery, /const overviewGroup = groups\.find/)
  assert.match(gallery, /setOverviewCollectionKey\(group\.key\)/)
  assert.match(gallery, /artifactLabel !== collectionLabel/)
  assert.match(gallery, /selected\.description !== selected\.collectionDescription/)
  assert.match(gallery, /const owningSessionId = artifact\.lineage\?\.parentSessionId \|\| artifact\.sessionId/)
  assert.doesNotMatch(gallery, /if \(!open \|\| !selected\) return undefined\s+setSelectedId\(artifactSelectionKey\(selected\)\)/)
  assert.doesNotMatch(gallery, /DesktopPlanExecutionSidebar/)
})

test('gallery chat actions emit opaque references and persist use before callback', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /export interface DesktopV3ArtifactChatSelection/)
  assert.match(gallery, /selection: DesktopV3ArtifactSelection/)
  assert.match(gallery, /onAddToChat\(pendingChatArtifacts\.map\(\(artifact\) => \{/)
  assert.match(gallery, /messageSelection = desktopV3ArtifactMessageSelection\(artifact, 'select'\)/)
  assert.match(gallery, /description: messageSelection\.description/)
  assert.match(gallery, /canonicalSelection = await useDesktopV3Artifact\(desktopV3ArtifactSelection\(selected\)\)/)
  assert.match(gallery, /messageSelection = desktopV3ArtifactMessageSelection\(selected, 'use'\)/)
  assert.match(gallery, /description: messageSelection\.description, selection: canonicalSelection/)
  assert.match(gallery, /data-artifact-selected-design/)
  assert.match(gallery, /Attach.*for changes<\/span>/)
  assert.match(gallery, /Ask for changes to remix the exact selected image/)
  assert.match(gallery, /Use this design<\/button>/)
  assert.doesNotMatch(gallery, /arrayBuffer\(\)/)
  assert.doesNotMatch(gallery, /onAddToChat\(\{[^}]*content:/)
  assert.doesNotMatch(gallery, /arrayBuffer\(\).*onAddToChat/)
})

test('gallery exposes the exact-reference HTML-to-video-stills bridge without browser capture or render authority', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /data-artifact-export-video-stills/)
  assert.match(gallery, /Video stills/)
  assert.match(gallery, /desktopV3ArtifactCanExportHTMLStills\(selected\)/)
  assert.match(gallery, /desktopV3ArtifactSelection\(selected\)/)
  assert.match(gallery, /DESKTOP_V3_HTML_STILL_EXPORT_PROMPT/)
  assert.match(gallery, /refreshOpenDesktopV3ArtifactCatalogs\(\)/)
  assert.match(gallery, /The managed PNGs will appear here when ready/)
  assert.match(gallery, /setActionPending\('export-video-stills'\)/)
  assert.match(gallery, /setActionError\(error instanceof Error \? error\.message : 'Could not request video-ready still export'\)/)
  assert.doesNotMatch(gallery, /html2canvas/)
  assert.doesNotMatch(gallery, /drawImage\(.*iframe/)
  assert.doesNotMatch(gallery, /accept.*proposal/i)
  assert.doesNotMatch(gallery, /start.*render/i)
})

test('mobile gallery reserves a stable middle generation viewport between selectors and actions', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /data-mobile-artifact-three-zone-layout/)
  assert.match(gallery, /grid-rows-\[auto_minmax\(0,1fr\)_auto\]/)
  assert.match(gallery, /data-mobile-generation-selector/)
  assert.match(gallery, /aria-label="Select generation"/)
  assert.match(gallery, /data-mobile-generation-actions/)
  assert.match(gallery, /h-\[100dvh\] w-full/)
  assert.match(gallery, /safe-area-inset-bottom/)
  assert.doesNotMatch(gallery, /h-\[100dvh\] w-\[100dvw\].*data-artifact-review-surface/)
})

test('open catalog consumes realtime refresh demand and keeps previews sandboxed', async () => {
  const gallery = await readFile(galleryURL, 'utf8')

  assert.match(gallery, /useDesktopV3OpenArtifactCatalogRefresh\(open, refreshCatalog\)/)
  assert.match(gallery, /const catalog = await fetchDesktopV3ArtifactCatalogResult\(\)/)
  assert.match(gallery, /setArtifacts\(catalog\.artifacts\)/)
  assert.match(gallery, /sandbox="allow-scripts"/)
  assert.match(gallery, /sandbox=""/)
  assert.match(gallery, /referrerPolicy="no-referrer"/)
  assert.match(gallery, /selected\.mediaType\.startsWith\('image\/'\).*previewURL/)
  assert.match(gallery, /<img[^>]*src=\{previewURL\}/)
  assert.match(gallery, /fetchDesktopV3ArtifactPreviewAccess/)
  assert.match(gallery, /desktopV3ArtifactDirectContentURL/)
  assert.doesNotMatch(gallery, /srcDoc=/)
  assert.doesNotMatch(gallery, /URL\.createObjectURL\(/)
  assert.match(gallery, /data-artifact-video-player/)
  assert.match(gallery, /<video[^>]*src=\{previewURL\} controls/)
  assert.doesNotMatch(gallery, /selected\.mediaType === 'image\/svg\+xml'.*no inline preview/)
  assert.doesNotMatch(gallery, /allow-same-origin/)
})
