import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

test('plan execution adapts its desktop sidebar and shifts above the composer below 1300px', async () => {
  const paneSource = await readFile(new URL('./desktop-v3-existing-conversation-pane.tsx', import.meta.url), 'utf8')
  const sidebarSource = await readFile(new URL('./desktop-plan-execution-sidebar.tsx', import.meta.url), 'utf8')
  const planAgentSource = await readFile(new URL('./desktop-plan-agent-sidecar.tsx', import.meta.url), 'utf8')

  assert.match(paneSource, /min-\[1300px\]:grid-cols-\[minmax\(0,1fr\)_360px\]/)
  assert.match(paneSource, /min-\[1300px\]:grid-cols-\[minmax\(0,1fr\)_280px\]/)
  assert.match(paneSource, /min-\[1300px\]:grid-cols-\[minmax\(0,1fr\)_56px\]/)
  assert.match(paneSource, /desktop-sidebar-display|planSidebarDisplayMode|data-plan-sidebar-mode/)
  assert.match(sidebarSource, /min-\[1300px\]:flex/)
  assert.match(sidebarSource, /displayMode|data-plan-thin-rail|w-\[280px\]|w-\[56px\]/)
  assert.match(planAgentSource, /displayMode|w-\[280px\]|w-\[56px\]/)
  assert.match(paneSource, /PLAN_SIDEBAR_MEDIA_QUERY = "\(min-width: 1300px\)"/)
  assert.match(paneSource, /data-testid="desktop-plan-agent-composer-region"/)
  assert.match(paneSource, />Ask Swarm Plan</)
  assert.match(paneSource, /Waiting for your review · Talk through changes before approval/)
  assert.match(paneSource, /mobileInline[\s\S]*mobileOpen/)
  assert.doesNotMatch(paneSource, /onAskForChanges=\{index === 0/)
  const mobilePlanRegionIndex = paneSource.indexOf('data-testid="desktop-plan-agent-composer-region"')
  const pendingPlanComposerIndex = paneSource.indexOf('<DesktopV3ExistingConversationComposer', mobilePlanRegionIndex)
  assert.ok(mobilePlanRegionIndex >= 0 && pendingPlanComposerIndex > mobilePlanRegionIndex, 'mobile pending Plan waiting state should render immediately above the main composer')
  assert.match(paneSource.slice(mobilePlanRegionIndex, pendingPlanComposerIndex), /planAgentMobileOpen \? \(/[\s\S]*<DesktopPlanAgentSidecar/)
  assert.match(paneSource, /pendingPlanDocument && pendingPlanPermission && planSidebarViewport/)
  assert.match(paneSource, /data-testid="desktop-plan-execution-composer-region"/)
  assert.match(paneSource, /min-\[1300px\]:hidden"\s+data-testid="desktop-plan-execution-composer-region"/)

  const compactRegionIndex = paneSource.indexOf('data-testid="desktop-plan-execution-composer-region"')
  const composerIndex = paneSource.indexOf('<DesktopV3AgenticComposer', compactRegionIndex)
  assert.ok(compactRegionIndex >= 0 && composerIndex > compactRegionIndex, 'compact plan surface should render immediately before the composer')

  const compactRegion = paneSource.slice(compactRegionIndex, composerIndex)
  assert.match(compactRegion, /data-mobile-session-sidebar-toggle/)
  assert.match(compactRegion, /activeSidebarView === "artifacts"/)
  assert.match(compactRegion, /<DesktopV3ArtifactSidebar[\s\S]*embedded/)
  assert.match(compactRegion, /<DesktopPlanExecutionSidebar/)
  assert.match(compactRegion, /embedded/)
  assert.match(compactRegion, /busyAction=\{planExecutionBusyAction\}/)
  assert.match(compactRegion, /onAction=\{stablePlanExecutionAction\}/)
  assert.match(compactRegion, /belowActions=\{planSidebarBelowActions\}/)
  assert.doesNotMatch(compactRegion, />\s*Automatic\s*</)
  assert.match(compactRegion, /policyMode !== "automatic"/)
  assert.match(compactRegion, />\s*Review each\s*</)
})
