import assert from 'node:assert/strict'
import { readFileSync } from 'node:fs'
import test from 'node:test'

const paneSource = readFileSync(new URL('./desktop-v3-existing-conversation-pane.tsx', import.meta.url), 'utf8')
const markdownSource = readFileSync(new URL('./chat-markdown.tsx', import.meta.url), 'utf8')

test('live and durable plan transitions use full-width minimal cards', () => {
  assert.match(markdownSource, /className="mb-2 w-full min-w-0 py-1.5" data-plan-tool-transition/)
  assert.match(markdownSource, /w-full min-w-0 rounded-xl border border-\[var\(--app-border\)\] bg-\[var\(--app-surface-subtle\)\]/)
  assert.match(markdownSource, /function ExitPlanModeToolView/)
  assert.match(markdownSource, /data-exit-plan-mode-transition/)
  assert.match(markdownSource, /Plan approved/)
  assert.match(markdownSource, /Execution continues/)
  assert.match(markdownSource, /if \(isExitPlanMode\) return <ExitPlanModeToolView/)
  const exitTransitionStart = markdownSource.indexOf('function ExitPlanModeToolView')
  const planManageStart = markdownSource.indexOf('function PlanManageToolView', exitTransitionStart)
  assert.ok(exitTransitionStart >= 0 && planManageStart > exitTransitionStart)
  const exitTransitionSource = markdownSource.slice(exitTransitionStart, planManageStart)
  assert.match(exitTransitionSource, /border border-\[var\(--app-border\)\] bg-\[var\(--app-surface-subtle\)\]/)
  assert.doesNotMatch(exitTransitionSource, /linear-gradient|shadow-sm/)
  assert.doesNotMatch(markdownSource, /data-plan-tool-transition[^]*border-l-2/)

  const toolWrapperStart = paneSource.indexOf('function DesktopV3ToolMessage')
  const reasoningStart = paneSource.indexOf('function DesktopV3ReasoningMessage', toolWrapperStart)
  assert.ok(toolWrapperStart >= 0 && reasoningStart > toolWrapperStart)
  const toolWrapperSource = paneSource.slice(toolWrapperStart, reasoningStart)
  assert.match(toolWrapperSource, /"plan-manage", "plan_manage", "exit-plan-mode", "exit_plan_mode"/)
  assert.match(toolWrapperSource, /usesFullWidthCard \? "w-full max-w-full" : "max-w-\[calc\(100%-2rem\)\]"/)

  const lifecycleStart = paneSource.indexOf('function DesktopV3PlanExecutionBreak')
  const handoffStart = paneSource.indexOf('function DesktopV3PlanCheckpointHandoff')
  assert.ok(lifecycleStart >= 0 && handoffStart > lifecycleStart)
  const lifecycleSource = paneSource.slice(lifecycleStart, handoffStart)
  assert.match(lifecycleSource, /flex w-full min-w-0 justify-start/)
  assert.match(lifecycleSource, /w-full min-w-0 rounded-xl border border-\[var\(--app-border\)\] bg-\[var\(--app-surface-subtle\)\]/)
  assert.doesNotMatch(lifecycleSource, /max-w-/)
  assert.doesNotMatch(lifecycleSource, /border-l-2/)

  const reviewParserStart = paneSource.indexOf('function parseDesktopV3CheckpointReviewCard')
  const reviewCardStart = paneSource.indexOf('function DesktopV3CheckpointReviewCardView', reviewParserStart)
  assert.ok(reviewParserStart >= 0 && reviewCardStart > reviewParserStart && lifecycleStart > reviewCardStart)
  const reviewParserSource = paneSource.slice(reviewParserStart, reviewCardStart)
  const reviewCardSource = paneSource.slice(reviewCardStart, lifecycleStart)
  assert.match(reviewParserSource, /action === "mark_needs_review"/)
  assert.match(reviewParserSource, /nextAction === "await_review"/)
  assert.match(reviewParserSource, /"Report"\|"Result"\|"Changed files"\|"Validation"/)
  assert.match(reviewCardSource, /data-testid="desktop-v3-checkpoint-review-card"/)
  assert.match(reviewCardSource, /aria-label="Checkpoint review"/)
  assert.match(reviewCardSource, /Review required/)
  assert.match(reviewCardSource, /Decision needed/)
  assert.match(reviewCardSource, /Full report/)
  assert.match(reviewCardSource, /Files changed \(\{card\.changedFiles\.length\}\)/)
  assert.match(reviewCardSource, /Validation · \{checkpointValidationSummary\(card\.validation\)\}/)
  assert.match(reviewCardSource, /<details>/)
  assert.match(lifecycleSource, /parseDesktopV3CheckpointReviewCard\(item\)/)
  assert.match(lifecycleSource, /<DesktopV3CheckpointReviewCardView item=\{item\} card=\{reviewCard\} \/>/)

  const checkpointStart = paneSource.indexOf('function DesktopV3PlanCheckpointHandoff')
  const finalStart = paneSource.indexOf('function DesktopV3PlanFinalHandoff', checkpointStart)
  const blockedStart = paneSource.indexOf('function DesktopV3PlanBlockedHandoff', finalStart)
  const sharedContentStart = paneSource.indexOf('function DesktopV3PlanHandoffContent', blockedStart)
  assert.ok(checkpointStart >= 0 && finalStart > checkpointStart && blockedStart > finalStart && sharedContentStart > blockedStart)

  const checkpointSource = paneSource.slice(checkpointStart, finalStart)
  assert.match(checkpointSource, /aria-label="Checkpoint handoff"/)
  assert.match(checkpointSource, /border-\[color-mix\(in_srgb,var\(--app-primary\)_35%,var\(--app-border\)\)\]/)
  assert.match(checkpointSource, /<DesktopV3PlanHandoffContent item=\{item\} \/>/)

  const blockedSource = paneSource.slice(blockedStart, sharedContentStart)
  assert.match(blockedSource, /aria-label="Blocked checkpoint handoff"/)
  assert.match(blockedSource, /data-checkpoint-status="blocked"/)
  assert.match(blockedSource, /border-\[color-mix\(in_srgb,var\(--app-warning\)_45%,var\(--app-border\)\)\]/)
  assert.match(blockedSource, /bg-\[var\(--app-warning-bg\)\]/)
  assert.match(blockedSource, /<DesktopV3PlanHandoffContent item=\{item\} \/>/)

  const structuredFinalStart = paneSource.indexOf('function DesktopV3StructuredFinalHandoff')
  const blockedAfterFinal = paneSource.indexOf('function DesktopV3PlanBlockedHandoff', structuredFinalStart)
  const finalSource = paneSource.slice(structuredFinalStart, blockedAfterFinal)
  assert.match(finalSource, /aria-label="Final handoff"/)
  assert.match(finalSource, /data-testid="desktop-v3-structured-final-handoff"/)
  assert.doesNotMatch(finalSource, /data-checkpoint-status="blocked"/)

  assert.match(paneSource, /function DesktopV3PlanHandoff/)
  assert.match(paneSource, /className="flex w-full min-w-0 justify-start py-1" data-testid=\{testId\}/)
  assert.match(paneSource, /function DesktopV3PlanHandoffContent/)
  assert.match(paneSource, /aria-label="At a glance"[^]*className="mt-3 w-full min-w-0 rounded-lg/)
  assert.match(paneSource, /<ChatMarkdown content=\{item\.summary\} \/>/)
  assert.match(paneSource, /<ChatMarkdown content=\{item\.body\} \/>/)
})
