import { useState } from 'react'
import { useMutation, useQuery, useQueryClient } from '@tanstack/react-query'
import { UserRound } from 'lucide-react'
import { Card } from '../../../../../components/ui/card'
import { fetchDesktopOnboardingStatus, upgradeAccountToTeam } from '../../../onboarding/api'

export function AccountSettingsPage() {
  const queryClient = useQueryClient()
  const [teamName, setTeamName] = useState('')
  const query = useQuery({
    queryKey: ['desktop-onboarding-status', 'account-settings'],
    queryFn: fetchDesktopOnboardingStatus,
    staleTime: 10_000,
  })
  const upgradeMutation = useMutation({
    mutationFn: (name: string) => upgradeAccountToTeam(name),
    onSuccess: async () => {
      setTeamName('')
      await queryClient.invalidateQueries({ queryKey: ['desktop-onboarding-status'] })
      await query.refetch()
    },
  })

  const identity = query.data?.identity
  const bootstrapped = Boolean(identity?.bootstrapped && identity.userID.trim() !== '')
  const hasTeam = Boolean(identity?.teamID.trim())
  const trimmedTeamName = teamName.trim()

  return (
    <div className="grid gap-6">
      <div className="grid gap-2">
        <div className="flex items-center gap-3">
          <div className="grid h-10 w-10 place-items-center rounded-2xl border border-[var(--app-border)] bg-[var(--app-surface-subtle)] text-[var(--app-text)]">
            <UserRound size={18} />
          </div>
          <div>
            <h2 className="text-2xl font-semibold tracking-tight text-[var(--app-text)]">Account</h2>
            <p className="text-sm text-[var(--app-text-muted)]">Product actor and account scope for this local daemon.</p>
          </div>
        </div>
      </div>

      {query.error ? (
        <Card className="border-[var(--app-warning-border)] bg-[var(--app-warning-bg)] p-4 text-sm text-[var(--app-warning)]">
          Account context is unavailable: {query.error instanceof Error ? query.error.message : 'failed to load account context'}
        </Card>
      ) : null}

      {!query.error && !bootstrapped ? (
        <Card className="border-[var(--app-warning-border)] bg-[var(--app-warning-bg)] p-5 text-sm leading-6 text-[var(--app-warning)]">
          No product user exists yet. Complete onboarding to create the initial local owner identity for this installed daemon.
        </Card>
      ) : null}

      {bootstrapped && identity ? (
        <>
          <Card className="grid gap-4 border-[var(--app-border)] bg-[var(--app-surface-subtle)] p-5">
            <ReadonlyAccountRow label="Username" value={identity.username || '—'} />
            <ReadonlyAccountRow label="User ID" value={identity.userID} />
            <ReadonlyAccountRow label="Account scope" value={identity.accountScopeID || '—'} />
            <ReadonlyAccountRow label="Team mode" value={hasTeam ? 'Team shared' : 'User private'} />
            {hasTeam ? (
              <>
                <ReadonlyAccountRow label="Team name" value={identity.teamDisplayName || '—'} />
                <ReadonlyAccountRow label="Team ID" value={identity.teamID} />
                <ReadonlyAccountRow label="Membership role" value={identity.membershipRole || '—'} />
              </>
            ) : null}
            <p className="text-xs leading-5 text-[var(--app-text-muted)]">
              Onboarding creates a user and account scope only. Team mode is created only by the explicit upgrade action below.
            </p>
          </Card>

          {!hasTeam ? (
            <Card className="grid gap-4 border-[var(--app-border)] bg-[var(--app-surface)] p-5">
              <div className="grid gap-1">
                <h3 className="text-base font-semibold text-[var(--app-text)]">Upgrade to Team</h3>
                <p className="text-sm leading-6 text-[var(--app-text-muted)]">
                  Create one shared team for this account scope. The internal team identifier is generated by the backend.
                  Existing private resources and credentials stay private.
                </p>
              </div>
              <form
                className="grid gap-3"
                onSubmit={(event) => {
                  event.preventDefault()
                  if (!trimmedTeamName || upgradeMutation.isPending) return
                  upgradeMutation.mutate(trimmedTeamName)
                }}
              >
                <label className="grid gap-2 text-sm font-medium text-[var(--app-text)]">
                  Team Name
                  <input
                    type="text"
                    value={teamName}
                    onChange={(event) => setTeamName(event.target.value)}
                    placeholder="Example: Acme Research"
                    className="rounded-xl border border-[var(--app-border)] bg-[var(--app-surface-subtle)] px-3 py-2 text-sm text-[var(--app-text)] outline-none focus:border-[var(--app-accent)]"
                    autoComplete="organization"
                  />
                </label>
                {upgradeMutation.error ? (
                  <div className="rounded-xl border border-[var(--app-warning-border)] bg-[var(--app-warning-bg)] px-3 py-2 text-sm text-[var(--app-warning)]">
                    {upgradeMutation.error instanceof Error ? upgradeMutation.error.message : 'Failed to upgrade account to team'}
                  </div>
                ) : null}
                <div>
                  <button
                    type="submit"
                    disabled={!trimmedTeamName || upgradeMutation.isPending}
                    className="rounded-xl border border-[var(--app-border)] bg-[var(--app-accent)] px-4 py-2 text-sm font-semibold text-[var(--app-background)] disabled:cursor-not-allowed disabled:opacity-50"
                  >
                    {upgradeMutation.isPending ? 'Upgrading…' : 'Upgrade to Team'}
                  </button>
                </div>
              </form>
            </Card>
          ) : (
            <Card className="border-[var(--app-success-border)] bg-[var(--app-success-bg)] p-5 text-sm leading-6 text-[var(--app-success)]">
              Team mode is enabled for {identity.teamDisplayName || 'this account'}. A second team cannot be created for the same account scope.
            </Card>
          )}
        </>
      ) : null}
    </div>
  )
}

function ReadonlyAccountRow({ label, value }: { label: string; value: string }) {
  return (
    <div className="grid gap-1 rounded-xl border border-[var(--app-border)] bg-[var(--app-surface)] px-4 py-3">
      <div className="text-xs font-medium uppercase tracking-[0.18em] text-[var(--app-text-muted)]">{label}</div>
      <div className="break-all text-sm font-medium text-[var(--app-text)]">{value}</div>
    </div>
  )
}
