/**
 * GCP Compute Engine (GCE) deployment provider.
 * Implements VM provisioning for dedicated, continuous, or Free Tier Swarm instances.
 */

import type {
  CloudDeployProvider,
  DeployCommand,
  DeployPlan,
  SwarmDeployManifest,
  ValidationResult,
} from '../types.js';

export class GcpComputeEngineProvider implements CloudDeployProvider {
  readonly target = 'gcp-compute-engine';

  validate(manifest: SwarmDeployManifest): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];

    const cfg = manifest.gcpCompute || {};
    const instanceName = cfg.instanceName || 'swarm-vm';

    if (!/^[a-z]([-a-z0-9]*[a-z0-9])?$/.test(instanceName) || instanceName.length > 63) {
      errors.push(
        `Invalid GCE instanceName '${instanceName}': must be lowercase alphanumeric with hyphens, <= 63 chars.`
      );
    }

    const machineType = cfg.machineType || 'e2-micro';
    if (machineType === 'e2-micro') {
      warnings.push(
        'e2-micro has 1GB RAM and no swap by default. Recommended for single-agent or up to 20 concurrent tasks; add swap if scaling higher.'
      );
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
    };
  }

  generateArtifacts(manifest: SwarmDeployManifest): Record<string, string> {
    const cfg = manifest.gcpCompute || {};
    const instanceName = cfg.instanceName || 'swarm-vm';
    const zone = cfg.zone || 'us-central1-a';
    const machineType = cfg.machineType || 'e2-micro';
    const diskSizeGb = cfg.diskSizeGb ?? 30;
    const diskType = cfg.diskType || 'pd-standard';
    const port = cfg.port ?? 18080;
    const serviceAccount = cfg.serviceAccount || '';
    const repoUrl = manifest.source.repository || 'https://github.com/swarm-agent/swarm';
    const branch = manifest.source.branch || 'main';
    const binaryUrl = manifest.source.binaryUrl || '';
    const isBinarySource = manifest.source.type === 'binary' || Boolean(binaryUrl);

    // Build environment variable lines for /etc/swarm/swarm.env
    const envLines: string[] = [
      `SWARM_LISTEN_ADDR=0.0.0.0:${port}`,
      `PORT=${port}`,
    ];
    if (manifest.context?.model) {
      envLines.push(`SWARM_MODEL=${manifest.context.model}`);
    }
    if (manifest.context?.thinking) {
      envLines.push(`SWARM_THINKING=${manifest.context.thinking}`);
    }
    if (manifest.env) {
      for (const [k, v] of Object.entries(manifest.env)) {
        envLines.push(`${k}=${v}`);
      }
    }

    const startupScript = `#!/usr/bin/env bash
# ==============================================================================
# Swarm Compute Engine Automated Startup & Context Management Script
# Generated by @swarm/sdk deploy module
# ==============================================================================
set -euo pipefail

echo "=== Initializing Swarm VM Daemon & Context ==="

# 1. Update packages and install prerequisites
export DEBIAN_FRONTEND=noninteractive
apt-get update -y
apt-get install -y --no-install-recommends git curl ca-certificates jq

# 2. Add swap space if on small instance (<2GB RAM) to prevent OOM
TOTAL_RAM_KB=$(grep MemTotal /proc/meminfo | awk '{print $2}')
if [ "$TOTAL_RAM_KB" -lt 2000000 ] && [ ! -f /swapfile ]; then
  echo "Allocating 2GB swap for memory headroom..."
  fallocate -l 2G /swapfile
  chmod 600 /swapfile
  mkswap /swapfile
  swapon /swapfile
  echo "/swapfile none swap sw 0 0" >> /etc/fstab
fi

# 3. Create dedicated system user and context directories
if ! id "swarm" &>/dev/null; then
  useradd -r -m -s /bin/bash -d /var/lib/swarm swarm
fi
mkdir -p /var/lib/swarm/context /var/lib/swarm/workspace /etc/swarm

# 4. Install prebuilt binary or compile Go daemon
SWARM_BIN="/usr/local/bin/swarmd"
if [ ! -f "$SWARM_BIN" ]; then
  ${
    isBinarySource
      ? `echo "Downloading precompiled Swarm daemon binary..."
  PREBUILT_URL="${binaryUrl || `${repoUrl}/releases/latest/download/swarmd-linux-amd64`}"
  if [[ "$PREBUILT_URL" =~ ^gs:// ]]; then
    gcloud storage cp "$PREBUILT_URL" "$SWARM_BIN"
  else
    curl -fsSL "$PREBUILT_URL" -o "$SWARM_BIN"
  fi
  chmod 755 "$SWARM_BIN"`
      : `echo "Installing Go compiler and building latest Swarm..."
  GO_TAR="go1.24.0.linux-amd64.tar.gz"
  curl -fsSL "https://go.dev/dl/$GO_TAR" -o "/tmp/$GO_TAR"
  rm -rf /usr/local/go && tar -C /usr/local -xzf "/tmp/$GO_TAR"
  export PATH="/usr/local/go/bin:$PATH"

  BUILD_DIR=$(mktemp -d)
  git clone --depth 1 --branch "${branch}" "${repoUrl}" "$BUILD_DIR"
  cd "$BUILD_DIR"
  CGO_ENABLED=0 /usr/local/go/bin/go build -trimpath -ldflags="-s -w" -o "$SWARM_BIN" ./cmd/swarmd
  chmod 755 "$SWARM_BIN"
  rm -rf "$BUILD_DIR" "/tmp/$GO_TAR"`
  }
fi

# 5. Populate initial environment configuration
cat << 'ENVEOF' > /etc/swarm/swarm.env
${envLines.join('\n')}
ENVEOF
chmod 600 /etc/swarm/swarm.env

# 6. Initialize Agent Context & Workspace
${
  manifest.context?.instructions
    ? `cat << 'INSTR_EOF' > /var/lib/swarm/context/AGENTS.md
${manifest.context.instructions}
INSTR_EOF`
    : '# No initial instructions provided'
}

${
  manifest.context?.prompt
    ? `cat << 'PROMPT_EOF' > /var/lib/swarm/context/PROMPT.txt
${manifest.context.prompt}
PROMPT_EOF`
    : '# No initial prompt provided'
}

${
  manifest.context?.workspaceUrl
    ? `if [ ! -d /var/lib/swarm/workspace/.git ]; then
  echo "Cloning workspace from ${manifest.context.workspaceUrl}..."
  git clone --depth 1 ${manifest.context.workspaceBranch ? `--branch "${manifest.context.workspaceBranch}"` : ''} "${manifest.context.workspaceUrl}" /var/lib/swarm/workspace || true
fi`
    : '# Default local workspace'
}

# 7. Install dynamic GCP metadata context sync utility
cat << 'SYNCEOF' > /usr/local/bin/swarm-sync-context
#!/usr/bin/env bash
# Synchronizes agent instructions, prompts, and config dynamically from GCP instance metadata
set -euo pipefail
MD_URL="http://metadata.google.internal/computeMetadata/v1/instance/attributes"
CHANGED=0

# Sync instructions / AGENTS.md
if curl -sf -H "Metadata-Flavor: Google" "$MD_URL/swarm-instructions" > /tmp/md_agents.md 2>/dev/null; then
  if [ -s /tmp/md_agents.md ] && ! cmp -s /tmp/md_agents.md /var/lib/swarm/context/AGENTS.md; then
    echo "Updating AGENTS.md from instance metadata..."
    mv /tmp/md_agents.md /var/lib/swarm/context/AGENTS.md
    CHANGED=1
  fi
fi

# Sync prompt / mission
if curl -sf -H "Metadata-Flavor: Google" "$MD_URL/swarm-prompt" > /tmp/md_prompt.txt 2>/dev/null; then
  if [ -s /tmp/md_prompt.txt ] && ! cmp -s /tmp/md_prompt.txt /var/lib/swarm/context/PROMPT.txt; then
    echo "Updating PROMPT.txt from instance metadata..."
    mv /tmp/md_prompt.txt /var/lib/swarm/context/PROMPT.txt
    CHANGED=1
  fi
fi

# Sync environment overrides
if curl -sf -H "Metadata-Flavor: Google" "$MD_URL/swarm-env" > /tmp/md_env 2>/dev/null; then
  if [ -s /tmp/md_env ]; then
    cat /tmp/md_env >> /etc/swarm/swarm.env
    CHANGED=1
  fi
fi

chown -R swarm:swarm /var/lib/swarm /etc/swarm
if [ "$CHANGED" -eq 1 ]; then
  echo "Context updated. Reloading Swarm daemon..."
  systemctl restart swarmd || true
fi
SYNCEOF
chmod 755 /usr/local/bin/swarm-sync-context

# Run initial metadata sync to catch any attributes passed on VM creation
/usr/local/bin/swarm-sync-context || true

${
  manifest.context?.bootHook
    ? `# 8. Execute custom user boot hook
${manifest.context.bootHook}`
    : ''
}

chown -R swarm:swarm /var/lib/swarm /etc/swarm

# 9. Configure systemd unit with EnvironmentFile support
cat << 'EOF' > /etc/systemd/system/swarmd.service
[Unit]
Description=Swarm AI Coding Workspace Daemon
After=network.target

[Service]
Type=simple
User=swarm
Group=swarm
WorkingDirectory=/var/lib/swarm
EnvironmentFile=-/etc/swarm/swarm.env
ExecStart=/usr/local/bin/swarmd
Restart=always
RestartSec=5
LimitNOFILE=65536

[Install]
WantedBy=multi-user.target
EOF

# 10. Enable and start daemon
systemctl daemon-reload
systemctl enable --now swarmd

echo "Waiting for Swarm daemon to become healthy on port ${port}..."
for i in {1..30}; do
  if curl -fsSL "http://127.0.0.1:${port}/v1/system/health" > /dev/null 2>&1; then
    echo "Swarm daemon is ready and healthy!"
    exit 0
  fi
  sleep 1
done

echo "Swarm service started (awaiting initialization)."
`;

    const saArg = serviceAccount ? `  --service-account "${serviceAccount}" \\\n` : '';
    const deployScript = `#!/usr/bin/env bash
# ==============================================================================
# Swarm GCE VM Provisioning Script
# Generated by @swarm/sdk deploy module
# ==============================================================================
set -euo pipefail

INSTANCE_NAME="${instanceName}"
ZONE="${zone}"
MACHINE_TYPE="${machineType}"
DISK_SIZE="${diskSizeGb}GB"
DISK_TYPE="${diskType}"
PROJECT_ID="\${GCP_PROJECT_ID:-\${CLOUDSDK_CORE_PROJECT:-${cfg.projectId || '${PROJECT_ID}'}}}"

echo "=== Provisioning Swarm Compute Engine VM ==="
echo "Instance:     \${INSTANCE_NAME}"
echo "Zone:         \${ZONE}"
echo "Machine Type: \${MACHINE_TYPE}"
echo "Disk:         \${DISK_SIZE} (\${DISK_TYPE})"
echo "============================================"

# Provision instance with startup script and context metadata
gcloud compute instances create "\${INSTANCE_NAME}" \\
  --project "\${PROJECT_ID}" \\
  --zone "\${ZONE}" \\
  --machine-type "\${MACHINE_TYPE}" \\
  --boot-disk-size "\${DISK_SIZE}" \\
  --boot-disk-type "\${DISK_TYPE}" \\
  --image-family "debian-12" \\
  --image-project "debian-cloud" \\
  --tags "swarm-agent,http-server" \\
  --metadata-from-file "startup-script=startup-script.sh" \\
${saArg}  --scopes "cloud-platform" \\
  --quiet

echo "Instance created. Querying IP address..."
VM_IP=$(gcloud compute instances describe "\${INSTANCE_NAME}" --zone "\${ZONE}" --project "\${PROJECT_ID}" --format 'value(networkInterfaces[0].accessConfigs[0].natIP)')
echo "VM Public IP: \${VM_IP}"
echo "Daemon will be accessible on http://\${VM_IP}:${port} once startup completes."
`;

    const artifacts: Record<string, string> = {
      'startup-script.sh': startupScript,
      'deploy-vm.sh': deployScript,
    };

    if (manifest.context?.instructions) {
      artifacts['AGENTS.md'] = manifest.context.instructions;
    }
    if (manifest.context?.prompt) {
      artifacts['PROMPT.txt'] = manifest.context.prompt;
    }

    return artifacts;
  }

  generateCommands(manifest: SwarmDeployManifest): DeployCommand[] {
    const cfg = manifest.gcpCompute || {};
    const instanceName = cfg.instanceName || 'swarm-vm';
    const zone = cfg.zone || 'us-central1-a';
    const machineType = cfg.machineType || 'e2-micro';
    const diskSizeGb = cfg.diskSizeGb ?? 30;
    const diskType = cfg.diskType || 'pd-standard';
    const port = cfg.port ?? 18080;
    const projectId = cfg.projectId ? ` --project ${cfg.projectId}` : '';
    const saArg = cfg.serviceAccount ? ` --service-account ${cfg.serviceAccount}` : '';

    const mdFiles: string[] = ['startup-script=startup-script.sh'];
    if (manifest.context?.instructions) {
      mdFiles.push('swarm-instructions=AGENTS.md');
    }
    if (manifest.context?.prompt) {
      mdFiles.push('swarm-prompt=PROMPT.txt');
    }

    return [
      {
        title: 'Provision GCE Virtual Machine',
        command: `gcloud compute instances create ${instanceName}${projectId} --zone ${zone} --machine-type ${machineType} --boot-disk-size ${diskSizeGb}GB --boot-disk-type ${diskType} --image-family debian-12 --image-project debian-cloud --tags swarm-agent,http-server --metadata-from-file ${mdFiles.join(',')}${saArg} --scopes cloud-platform --quiet`,
        explanation: `Creates an ephemeral or persistent ${machineType} VM with automated startup script and dynamic metadata context synchronization for headless Swarm daemon hosting.`,
        phase: 'deploy',
      },
      {
        title: 'Inspect VM Status and Public IP',
        command: `gcloud compute instances describe ${instanceName}${projectId} --zone ${zone} --format 'table(name,status,networkInterfaces[0].accessConfigs[0].natIP:label=EXTERNAL_IP)'`,
        explanation: 'Retrieves external IP and verifies RUNNING status on the newly provisioned VM.',
        phase: 'verify',
      },
      {
        title: 'Teardown VM (Zero Waste Cleanup)',
        command: `gcloud compute instances delete ${instanceName}${projectId} --zone ${zone} --quiet`,
        explanation: 'Deletes the VM instance and attached boot disk when testing is completed to ensure zero lingering costs.',
        phase: 'cleanup',
      },
    ];
  }

  plan(manifest: SwarmDeployManifest): DeployPlan {
    const validation = this.validate(manifest);
    const artifacts = this.generateArtifacts(manifest);
    const commands = this.generateCommands(manifest);
    const cfg = manifest.gcpCompute || {};
    const machineType = cfg.machineType || 'e2-micro';

    const costSummary = machineType === 'e2-micro'
      ? 'Eligible for GCP Free Tier (1 free e2-micro instance + 30GB disk per month = $0.00/mo).'
      : `Estimated compute cost: ~$0.021/hour (~$15/month) on standard on-demand pricing.`;

    return {
      manifest,
      target: this.target,
      summary: `Compute Engine VM deployment on ${machineType} in ${cfg.zone || 'us-central1-a'}. ${costSummary}`,
      artifacts,
      commands,
      recommendations: [
        'Automated swap allocation included for low-memory instances to prevent OOM termination.',
        'Runs as non-privileged system user under systemd with auto-restart.',
        'Dynamic context management via /usr/local/bin/swarm-sync-context and GCP metadata.',
        'Use IAP tunnel (gcloud compute start-iap-tunnel) for zero-public-IP private access.',
      ],
      warnings: validation.warnings,
    };
  }
}
