/**
 * GCP Cloud Run deployment provider.
 * Implements latency-optimized, scale-to-zero serverless deployment for Swarm.
 */

import { generateDockerIgnore, generateOptimizedDockerfile } from '../dockerfile.js';
import type {
  CloudDeployProvider,
  DeployCommand,
  DeployPlan,
  SwarmDeployManifest,
  ValidationResult,
} from '../types.js';

export class GcpCloudRunProvider implements CloudDeployProvider {
  readonly target = 'gcp-cloud-run';

  validate(manifest: SwarmDeployManifest): ValidationResult {
    const errors: string[] = [];
    const warnings: string[] = [];

    const cfg = manifest.gcpCloudRun || {};
    const serviceName = cfg.serviceName || 'swarmd';

    // Validate Cloud Run naming conventions (RFC 1123)
    if (!/^[a-z]([-a-z0-9]*[a-z0-9])?$/.test(serviceName) || serviceName.length > 63) {
      errors.push(
        `Invalid Cloud Run serviceName '${serviceName}': must be lowercase alphanumeric with hyphens, starting with a letter and <= 63 chars.`
      );
    }

    if (cfg.minInstances !== undefined && cfg.minInstances > 0) {
      warnings.push(
        `minInstances is set to ${cfg.minInstances}. This prevents cold starts but incurs continuous idle compute charges.`
      );
    }

    if (cfg.cpuBoost === false) {
      warnings.push(
        'cpuBoost is set to false. Enabling Startup CPU Boost reduces Go container cold starts by up to 50% (<1.5s).'
      );
    }

    if (cfg.executionEnvironment === 'gen1') {
      warnings.push(
        "executionEnvironment 'gen1' is legacy. 'gen2' is strongly recommended for lower cold-start overhead and modern Linux kernel features."
      );
    }

    return {
      valid: errors.length === 0,
      errors,
      warnings,
    };
  }

  generateArtifacts(manifest: SwarmDeployManifest): Record<string, string> {
    const cfg = manifest.gcpCloudRun || {};
    const serviceName = cfg.serviceName || 'swarmd';
    const region = cfg.region || 'us-central1';
    const projectId = cfg.projectId || '${PROJECT_ID}';
    const port = cfg.port ?? 18080;
    const cpu = cfg.cpu || '1';
    const memory = cfg.memory || '512Mi';
    const minInstances = cfg.minInstances ?? 0;
    const maxInstances = cfg.maxInstances ?? 10;
    const concurrency = cfg.concurrency ?? 80;
    const cpuBoost = cfg.cpuBoost !== false;
    const execEnv = cfg.executionEnvironment || 'gen2';
    const timeout = cfg.timeoutSeconds ?? 300;
    const allowUnauth = cfg.allowUnauthenticated ? '--allow-unauthenticated' : '--no-allow-unauthenticated';
    const ingress = cfg.ingress || 'all';

    const dockerfile = generateOptimizedDockerfile({
      source: manifest.source,
      port,
      strategy: manifest.source.buildStrategy || 'distroless',
    });

    const dockerignore = generateDockerIgnore();

    // Cloud Build configuration
    const cloudBuildYaml = `# Cloud Build specification for ${serviceName}
# Generated by @swarm/sdk deploy module
steps:
  # Build container image
  - name: 'gcr.io/cloud-builders/docker'
    args: ['build', '-t', 'gcr.io/${projectId}/${serviceName}:latest', '.']
  # Push container image to Artifact Registry / GCR
  - name: 'gcr.io/cloud-builders/docker'
    args: ['push', 'gcr.io/${projectId}/${serviceName}:latest']
  # Deploy to Cloud Run
  - name: 'gcr.io/google.com/cloudsdktool/cloud-sdk'
    entrypoint: gcloud
    args:
      - 'run'
      - 'deploy'
      - '${serviceName}'
      - '--image'
      - 'gcr.io/${projectId}/${serviceName}:latest'
      - '--region'
      - '${region}'
      - '--platform'
      - 'managed'
      - '--cpu'
      - '${cpu}'
      - '--memory'
      - '${memory}'
      - '--concurrency'
      - '${concurrency}'
      - '--min-instances'
      - '${minInstances}'
      - '--max-instances'
      - '${maxInstances}'
      - '--port'
      - '${port}'
      ${cpuBoost ? "- '--cpu-boost'" : ''}
      - '--execution-environment'
      - '${execEnv}'
      - '--timeout'
      - '${timeout}s'
      - '${allowUnauth}'
      - '--ingress'
      - '${ingress}'
images:
  - 'gcr.io/${projectId}/${serviceName}:latest'
`;

    // Self-contained deploy shell script
    const envVarsArg = manifest.env && Object.keys(manifest.env).length > 0
      ? Object.entries(manifest.env).map(([k, v]) => `${k}=${v}`).join(',')
      : '';

    const secretVarsArg = manifest.secrets && Object.keys(manifest.secrets).length > 0
      ? Object.entries(manifest.secrets).map(([k, v]) => `${k}=${v}`).join(',')
      : '';

    const deployScript = `#!/usr/bin/env bash
# ==============================================================================
# Swarm Cloud Run Automated Deployment Script
# Generated by @swarm/sdk deploy module
# ==============================================================================
set -euo pipefail

SERVICE_NAME="${serviceName}"
REGION="${region}"
PROJECT_ID="\${GCP_PROJECT_ID:-\${CLOUDSDK_CORE_PROJECT:-${projectId}}}"
IMAGE_TAG="gcr.io/\${PROJECT_ID}/\${SERVICE_NAME}:latest"

echo "=== Deploying Swarm to Cloud Run ==="
echo "Service:  \${SERVICE_NAME}"
echo "Region:   \${REGION}"
echo "Project:  \${PROJECT_ID}"
echo "Image:    \${IMAGE_TAG}"
echo "====================================="

# Step 1: Submit build to Google Cloud Build
echo "Building container image with Cloud Build..."
gcloud builds submit --tag "\${IMAGE_TAG}" --project "\${PROJECT_ID}" .

# Step 2: Deploy to Cloud Run with optimal latency flags
echo "Deploying service to Cloud Run..."
gcloud run deploy "\${SERVICE_NAME}" \\
  --image "\${IMAGE_TAG}" \\
  --region "\${REGION}" \\
  --project "\${PROJECT_ID}" \\
  --platform managed \\
  --cpu "${cpu}" \\
  --memory "${memory}" \\
  --concurrency "${concurrency}" \\
  --min-instances "${minInstances}" \\
  --max-instances "${maxInstances}" \\
  --port "${port}" \\
  ${cpuBoost ? '--cpu-boost \\' : ''}
  --execution-environment "${execEnv}" \\
  --timeout "${timeout}s" \\
  ${allowUnauth} \\
  --ingress "${ingress}" \\
  ${envVarsArg ? `--set-env-vars "${envVarsArg}" \\` : ''}
  ${secretVarsArg ? `--set-secrets "${secretVarsArg}" \\` : ''}
  --quiet

# Step 3: Fetch service URL and verify health
SERVICE_URL=$(gcloud run services describe "\${SERVICE_NAME}" --region "\${REGION}" --project "\${PROJECT_ID}" --format 'value(status.url)')
echo "Service successfully deployed at: \${SERVICE_URL}"

echo "Verifying service health..."
if curl -fsSL "\${SERVICE_URL}/v1/system/health" > /dev/null 2>&1; then
  echo "Swarm health check PASSED!"
else
  echo "Service is live at \${SERVICE_URL} (authenticated endpoint)."
fi
`;

    return {
      Dockerfile: dockerfile,
      '.dockerignore': dockerignore,
      'cloudbuild.yaml': cloudBuildYaml,
      'deploy.sh': deployScript,
    };
  }

  generateCommands(manifest: SwarmDeployManifest): DeployCommand[] {
    const cfg = manifest.gcpCloudRun || {};
    const serviceName = cfg.serviceName || 'swarmd';
    const region = cfg.region || 'us-central1';
    const projectId = cfg.projectId || '${PROJECT_ID}';
    const port = cfg.port ?? 18080;
    const cpu = cfg.cpu || '1';
    const memory = cfg.memory || '512Mi';
    const minInstances = cfg.minInstances ?? 0;
    const maxInstances = cfg.maxInstances ?? 10;
    const concurrency = cfg.concurrency ?? 80;
    const cpuBoost = cfg.cpuBoost !== false;
    const execEnv = cfg.executionEnvironment || 'gen2';
    const timeout = cfg.timeoutSeconds ?? 300;
    const allowUnauth = cfg.allowUnauthenticated ? '--allow-unauthenticated' : '--no-allow-unauthenticated';
    const ingress = cfg.ingress || 'all';

    const envFlags = manifest.env && Object.keys(manifest.env).length > 0
      ? ` --set-env-vars "${Object.entries(manifest.env).map(([k, v]) => `${k}=${v}`).join(',')}"`
      : '';

    const secretFlags = manifest.secrets && Object.keys(manifest.secrets).length > 0
      ? ` --set-secrets "${Object.entries(manifest.secrets).map(([k, v]) => `${k}=${v}`).join(',')}"`
      : '';

    const commands: DeployCommand[] = [
      {
        title: 'Build Container Image via Cloud Build',
        command: `gcloud builds submit --tag gcr.io/${projectId}/${serviceName}:latest .`,
        explanation:
          'Submits local build context to Cloud Build, compiling a stripped distroless container (<35MB) without requiring a local Docker daemon.',
        phase: 'build',
      },
      {
        title: 'Deploy Service to Cloud Run',
        command: `gcloud run deploy ${serviceName} --image gcr.io/${projectId}/${serviceName}:latest --region ${region} --platform managed --cpu ${cpu} --memory ${memory} --concurrency ${concurrency} --min-instances ${minInstances} --max-instances ${maxInstances} --port ${port}${cpuBoost ? ' --cpu-boost' : ''} --execution-environment ${execEnv} --timeout ${timeout}s ${allowUnauth} --ingress ${ingress}${envFlags}${secretFlags} --quiet`,
        explanation:
          'Provisions serverless Cloud Run instance with Startup CPU Boost and gen2 execution environment for sub-1.5s cold starts and scale-to-zero ($0 idle cost).',
        phase: 'deploy',
      },
      {
        title: 'Query Service URL and Verify Health',
        command: `SERVICE_URL=$(gcloud run services describe ${serviceName} --region ${region} --format 'value(status.url)') && curl -fsSL "$SERVICE_URL/v1/system/health" || echo "Service URL: $SERVICE_URL"`,
        explanation: 'Retrieves the public/private URL and runs an HTTP probe against /v1/system/health.',
        phase: 'verify',
      },
    ];

    return commands;
  }

  plan(manifest: SwarmDeployManifest): DeployPlan {
    const validation = this.validate(manifest);
    const artifacts = this.generateArtifacts(manifest);
    const commands = this.generateCommands(manifest);
    const cfg = manifest.gcpCloudRun || {};
    const serviceName = cfg.serviceName || 'swarmd';

    const minInstances = cfg.minInstances ?? 0;
    const costSummary = minInstances === 0
      ? '$0.00/month idle cost (true scale-to-zero). Only billed when active (~$0.00174/minute of CPU/RAM during requests).'
      : `Billed for ${minInstances} warm instance (~$7-$12/month) to ensure 0ms cold starts.`;

    const recommendations = [
      'Startup CPU Boost enabled: cuts container initialization time by ~50% (<1.5s cold start).',
      'Distroless static container: shrinks image to <35MB for sub-second layer downloads.',
      'Execution Environment gen2: provides faster gVisor runtime overhead and modern Linux kernel.',
      'No UPX compression: keeps binary uncompressed to avoid CPU startup decompression delays.',
      minInstances === 0
        ? 'Scale-to-zero active: ideal for AI agent webhooks and episodic developer workflows.'
        : 'Warm pool active: ideal for interactive low-latency user chat.',
    ];

    return {
      manifest,
      target: this.target,
      summary: `Cloud Run serverless deployment for '${serviceName}'. ${costSummary}`,
      artifacts,
      commands,
      recommendations,
      warnings: validation.warnings,
    };
  }
}
