import { automationControl as control } from './automation-editor'

export const automationStarters = [
  { id: 'overnight', title: 'Overnight supervision', availability: 'Limited · planning only', description: 'Design a bounded review. Continuous blocker monitoring and automatic unblocking are not available here.', prompt: 'Help me plan an overnight workspace review. Explain which scheduled checks are supported and which continuous monitoring or unblock capabilities are unavailable. Propose a bounded, read-only summary with an expiry. Do not enable execution or automatically unblock sessions.' },
  { id: 'archive', title: 'Archive readiness', availability: 'Available in chat · explicit review', description: 'Ask for evidence-based archive candidates. Archiving still needs a separate approval; this is not an automatic archive trigger.', prompt: 'Review my needs-review sessions for archive readiness using the supported session review tools. Separate safe candidates from dirty or unfinished work and explain the evidence. Do not archive, integrate, commit, or enable an automation without my separate approval.' },
  { id: 'testing', title: 'Ready-to-test summary', availability: 'Available in chat · source review', description: 'Organize changes, proposed checks and blockers. Running tests or changing sessions requires the applicable permission.', prompt: 'Summarize the workspace work that is ready to test. Identify changed areas, proposed focused commands, and unresolved blockers. Distinguish source inspection from executed evidence. Do not run tests, change session states, or enable execution. Help me turn this into a reviewed automation plan if supported.' },
] as const

export function AutomationOverview({ onPrompt, onUpdates }: { onPrompt: (prompt: string) => void; onUpdates: () => void }) {
  return <main className="min-w-0 flex-1 space-y-8 p-4 lg:p-6">
    <header className="space-y-3"><p className="text-sm text-[var(--app-text-muted)]">WORKSPACE AUTOMATIONS</p><h2 className="text-3xl font-semibold">Plan once. Stay in control.</h2><p className="max-w-2xl text-[var(--app-text-muted)]">Turn a repeatable task into a reviewed plan. Start with the AI sidebar, choose when it runs, and approve its exact scope before enabling it.</p><div className="flex flex-wrap gap-2"><button className={control} onClick={() => onPrompt('Help me design an automation for this workspace. Ask about the task, trigger, expected output, permissions and expiry. Draft a plan for review; do not save, approve, enable or run anything yet.')}>Plan an automation</button><button className={control} onClick={onUpdates}>View outcomes and history</button><a className={control} href="#automation-ai">Go to AI sidebar</a></div></header>
    <section aria-label="How automations work" className="space-y-3"><h3 className="text-lg font-semibold">What you define</h3><dl className="grid gap-3 sm:grid-cols-2">{[
      ['Trigger', 'Manual, interval or cron schedules. Event intake requires the approving user and an exact enabled policy/source; this page does not configure external webhooks or session watchers.'],
      ['Conditions', 'Define prerequisites in the reviewed plan. Missed-run and overlap policies control scheduling; there is no general condition-builder here.'],
      ['Instructions', 'Pin exact reviewed plan revisions. Later chat messages do not silently replace those instructions.'],
      ['Permissions', 'Review workspace, tools, targets and expiry. Normal permissions still apply; chat is not an execution grant.'],
      ['Outputs', 'Inspect recorded outcomes, occurrence conversations and their artifacts. An admitted run is not proof of success.'],
      ['Approval', 'Review plan → save draft → approve execution policy → enable. These remain separate decisions.'],
    ].map(([title, text]) => <div key={title} className="rounded-xl border border-[var(--app-border)] p-4"><dt className="mb-2 font-semibold">{title}</dt><dd className="text-sm text-[var(--app-text-muted)]">{text}</dd></div>)}</dl></section>
    <section aria-label="Starter ideas" className="space-y-3"><h3 className="text-lg font-semibold">Start with an idea</h3><p className="text-sm">Examples fill an editable draft. Nothing is sent, saved or enabled automatically.</p><div className="grid gap-3">{automationStarters.map(starter => <article key={starter.id} className="space-y-3 rounded-xl border border-[var(--app-border)] p-4"><div><h4 className="font-semibold">{starter.title}</h4><p className="text-xs text-[var(--app-text-muted)]">{starter.availability}</p></div><p className="text-sm">{starter.description}</p><button className={control} onClick={() => onPrompt(starter.prompt)}>Customize {starter.title.toLowerCase()}</button></article>)}</div></section>
  </main>
}
