package api

import (
	"encoding/json"
	"errors"
	"net/http"
	"strings"

	"swarm/packages/swarmd/internal/identity"
)

type accountUsernameUpdateRequest struct {
	Username string `json:"username"`
}

type accountTeamUpgradeRequest struct {
	TeamName string `json:"team_name"`
	TeamID   string `json:"team_id,omitempty"`
}

type accountTeamSummary struct {
	ID             string `json:"id"`
	AccountScopeID string `json:"account_scope_id"`
	DisplayName    string `json:"display_name"`
	MembershipRole string `json:"membership_role"`
}

func (s *Server) handleAccountUsername(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPut {
		methodNotAllowed(w)
		return
	}
	actor, ok := s.requireProductActor(w, r)
	if !ok {
		return
	}
	var req accountUsernameUpdateRequest
	if err := decodeJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, err)
		return
	}
	if s == nil || s.identityService == nil {
		writeError(w, http.StatusInternalServerError, identity.ErrServiceNotConfigured)
		return
	}
	updated, err := s.identityService.RenameCurrentUser(actor, req.Username)
	if err != nil {
		switch {
		case errors.Is(err, identity.ErrUsernameAlreadyExists):
			writeError(w, http.StatusConflict, err)
		case errors.Is(err, identity.ErrUserRenameUnauthorized):
			writeError(w, http.StatusForbidden, err)
		default:
			writeError(w, http.StatusBadRequest, err)
		}
		return
	}
	if s.events != nil {
		if payload, err := json.Marshal(map[string]string{
			"account_scope_id": updated.AccountScopeID,
			"user_id":          updated.ID,
			"username":         updated.Username,
		}); err == nil {
			_, _ = s.events.Append("identity:user:"+updated.ID, "identity.user.renamed", updated.ID, payload, "", "")
		}
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"ok":       true,
		"userID":   updated.ID,
		"user_id":  updated.ID,
		"username": updated.Username,
	})
}

func (s *Server) handleAccountTeamUpgrade(w http.ResponseWriter, r *http.Request) {
	if r.Method != http.MethodPost {
		methodNotAllowed(w)
		return
	}
	actor, ok := s.requireProductActor(w, r)
	if !ok {
		return
	}
	var req accountTeamUpgradeRequest
	if err := decodeJSON(r, &req); err != nil {
		writeError(w, http.StatusBadRequest, err)
		return
	}
	if strings.TrimSpace(req.TeamID) != "" {
		writeError(w, http.StatusBadRequest, errors.New("team_id is generated by the server and must not be supplied"))
		return
	}
	if s == nil || s.identityService == nil {
		writeError(w, http.StatusInternalServerError, identity.ErrServiceNotConfigured)
		return
	}
	result, err := s.identityService.UpgradeAccountToTeam(actor, req.TeamName)
	if err != nil {
		switch {
		case errors.Is(err, identity.ErrTeamAlreadyExists):
			writeError(w, http.StatusConflict, err)
		case errors.Is(err, identity.ErrTeamOptInUnauthorized):
			writeError(w, http.StatusForbidden, err)
		default:
			writeError(w, http.StatusBadRequest, err)
		}
		return
	}
	if s.events != nil {
		if payload, err := json.Marshal(map[string]string{
			"account_scope_id": result.Team.AccountScopeID,
			"team_id":          result.Team.ID,
			"team_name":        result.Team.Name,
			"user_id":          result.Membership.UserID,
		}); err == nil {
			_, _ = s.events.Append("identity:account:"+result.Team.AccountScopeID, "identity.account.team_upgraded", result.Team.ID, payload, "", "")
		}
	}
	if s.identitySessions != nil {
		if issued, err := s.identitySessions.IssueForCurrentSelection(); err == nil {
			http.SetCookie(w, buildDesktopLocalSessionCookie(issued.Token, issued.ExpiresAt, requestScheme(r) == "https"))
		}
	}
	writeJSON(w, http.StatusOK, map[string]any{
		"ok": true,
		"team": accountTeamSummary{
			ID:             result.Team.ID,
			AccountScopeID: result.Team.AccountScopeID,
			DisplayName:    result.Team.Name,
			MembershipRole: result.Membership.Role,
		},
	})
}
