package api

import "net/http"

func (s *Server) registerCoreRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/healthz", s.handleHealth)
	mux.HandleFunc("/readyz", s.handleReady)
	mux.HandleFunc("/ws", s.handleDesktopStream)
}

func (s *Server) registerAuthVaultRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/auth/codex", s.handleCodexAuth)
	mux.HandleFunc("/v1/auth/codex/oauth/start", s.handleCodexOAuthStart)
	mux.HandleFunc("/v1/auth/codex/oauth/status", s.handleCodexOAuthStatus)
	mux.HandleFunc("/v1/auth/codex/oauth/complete", s.handleCodexOAuthComplete)
	mux.HandleFunc("/v1/auth/credentials", s.handleAuthCredentials)
	mux.HandleFunc("/v1/auth/credentials/verify", s.handleAuthCredentialVerify)
	mux.HandleFunc("/v1/auth/credentials/active", s.handleAuthCredentialActive)
	mux.HandleFunc("/v1/auth/credentials/delete", s.handleAuthCredentialDelete)
	mux.HandleFunc("/v1/auth/desktop/session", s.handleDesktopLocalSessionBootstrap)
	mux.HandleFunc("/v1/auth/attach/rotate", s.handleAttachRotate)
	mux.HandleFunc("/v1/vault", s.handleVaultStatus)
	mux.HandleFunc("/v1/vault/enable", s.handleVaultEnable)
	mux.HandleFunc("/v1/vault/unlock", s.handleVaultUnlock)
	mux.HandleFunc("/v1/vault/lock", s.handleVaultLock)
	mux.HandleFunc("/v1/vault/disable", s.handleVaultDisable)
	mux.HandleFunc("/v1/vault/export", s.handleVaultExport)
	mux.HandleFunc("/v1/vault/import", s.handleVaultImport)
}

func (s *Server) registerOnboardingRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/me", s.handleMe)
	mux.HandleFunc("/v1/me", s.handleMe)
	mux.HandleFunc("/v1/onboarding", s.handleOnboarding)
	mux.HandleFunc("/v1/onboarding/provider/credential", s.handleOnboardingProviderCredential)
	mux.HandleFunc("/v1/account/team/upgrade", s.handleAccountTeamUpgrade)
}

func (s *Server) registerSwarmRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/swarm/targets", s.handleSwarmTargets)
	mux.HandleFunc("/v1/swarm/target/current", s.handleSwarmCurrentTarget)
	mux.HandleFunc("/v1/swarm/target/select", s.handleSwarmSelectTarget)
	mux.HandleFunc("/v1/swarm/groups", s.handleSwarmGroups)
	mux.HandleFunc("/v1/swarm/groups/upsert", s.handleSwarmGroupUpsert)
	mux.HandleFunc("/v1/swarm/groups/current", s.handleSwarmCurrentGroup)
	mux.HandleFunc("/v1/swarm/groups/members/delete", s.handleSwarmGroupMemberDelete)
	mux.HandleFunc("/v1/swarm/containers/profiles", s.handleSwarmContainerProfiles)
	mux.HandleFunc("/v1/swarm/containers/profiles/upsert", s.handleSwarmContainerProfileUpsert)
	mux.HandleFunc("/v1/swarm/containers/profiles/delete", s.handleSwarmContainerProfileDelete)
	mux.HandleFunc("/v1/swarm/topology", s.handleSwarmTopologySnapshot)
	mux.HandleFunc("/v1/swarm/topology/workspace-bindings", s.handleSwarmTopologyWorkspaceBindings)
}

func (s *Server) registerDeployRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/deploy/container/runtime", s.handleDeployContainerRuntime)
	mux.HandleFunc("/v1/deploy/container", s.handleDeployContainers)
	mux.HandleFunc("/v1/deploy/container/create", s.handleDeployContainerCreate)
	mux.HandleFunc("/v1/deploy/container/package/defaults", s.handleDeployContainerPackageDefaults)
	mux.HandleFunc("/v1/deploy/container/package/validate", s.handleDeployContainerPackageValidate)
	mux.HandleFunc("/v1/deploy/container/package/suggest", s.handleDeployContainerPackageSuggest)
}

func (s *Server) registerAgentRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v2/custom-tools", s.handleCustomToolsV2)
	mux.HandleFunc("/v2/custom-tools/", s.handleCustomToolByNameV2)
	mux.HandleFunc("/v2/agents", s.handleAgentsV2)
	mux.HandleFunc("/v2/agents/defaults/restore", s.handleAgentDefaultsRestoreV2)
	mux.HandleFunc("/v2/agents/defaults/reset", s.handleAgentDefaultsResetV2)
	mux.HandleFunc("/v2/agents/", s.handleAgentByNameV2)
}

func (s *Server) registerProviderRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/codex/account/usage", s.handleCodexAccountUsage)
	mux.HandleFunc("/v1/codex/account/reset-credits", s.handleCodexResetCredits)
	mux.HandleFunc("/v1/codex/account/reset-credits/consume", s.handleCodexConsumeResetCredit)
	mux.HandleFunc("/v1/image/providers", s.handleImageGenerationProviders)
	mux.HandleFunc("/v1/image/generations", s.handleImageGenerations)
	mux.HandleFunc("/v1/image/assets", s.handleImageAssets)
	mux.HandleFunc("/v1/image/storage/reveal", s.handleImageStorageReveal)
	mux.HandleFunc("/v1/model", s.handleModelPreference)
	mux.HandleFunc("/v1/model/catalog", s.handleModelCatalog)
	mux.HandleFunc("/v1/model/catalog/check", s.handleModelCatalogCheck)
	mux.HandleFunc("/v1/models/favorites", s.handleModelFavorites)
	mux.HandleFunc("/v1/models/favorites/delete", s.handleModelFavoriteDelete)
	mux.HandleFunc("/v1/providers", s.handleProviders)
	mux.HandleFunc("/v1/stt/transcribe", s.handleSTTTranscribe)
	mux.HandleFunc("/v1/voice/status", s.handleVoiceStatus)
	mux.HandleFunc("/v1/voice/profiles", s.handleVoiceProfiles)
	mux.HandleFunc("/v1/voice/profiles/upsert", s.handleVoiceProfileUpsert)
	mux.HandleFunc("/v1/voice/profiles/delete", s.handleVoiceProfileDelete)
	mux.HandleFunc("/v1/voice/config", s.handleVoiceConfig)
	mux.HandleFunc("/v1/voice/devices", s.handleVoiceDevices)
	mux.HandleFunc("/v1/voice/test-stt", s.handleVoiceTestSTT)
}

func (s *Server) registerWorkspaceRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/ui/settings", s.handleUISettings)
	mux.HandleFunc("/v1/workspace/resolve", s.handleWorkspaceResolve)
	mux.HandleFunc("/v1/workspace/select", s.handleWorkspaceSelect)
	mux.HandleFunc("/v1/workspace/current", s.handleWorkspaceCurrent)
	mux.HandleFunc("/v1/workspace/list", s.handleWorkspaceList)
	mux.HandleFunc("/v1/workspace/overview", s.handleWorkspaceOverview)
	mux.HandleFunc("/v1/workspace/cwd/resolve", s.handleWorkspaceCWDResolve)
	mux.HandleFunc("/v1/workspace/discover", s.handleWorkspaceDiscover)
	mux.HandleFunc("/v1/workspace/browse", s.handleWorkspaceBrowse)
	mux.HandleFunc("/v1/workspace/video/scan", s.handleWorkspaceVideoScan)
	mux.HandleFunc("/v1/workspace/video/storage/reveal", s.handleVideoStorageReveal)
	mux.HandleFunc("/v1/workspace/video/threads", s.handleWorkspaceVideoThreads)
	mux.HandleFunc("/v1/workspace/video/threads/", s.handleWorkspaceVideoThread)
	mux.HandleFunc("/v1/workspace/image/threads", s.handleWorkspaceImageThreads)
	mux.HandleFunc("/v1/workspace/image/threads/", s.handleWorkspaceImageThread)
	mux.HandleFunc("/v1/workspace/folders/create", s.handleWorkspaceFolderCreate)
	mux.HandleFunc("/v1/workspace/add", s.handleWorkspaceAdd)
	mux.HandleFunc("/v1/workspace/directories/add", s.handleWorkspaceDirectoryAdd)
	mux.HandleFunc("/v1/workspace/directories/remove", s.handleWorkspaceDirectoryRemove)
	mux.HandleFunc("/v1/workspace/theme", s.handleWorkspaceTheme)
	mux.HandleFunc("/v1/workspace/rename", s.handleWorkspaceRename)
	mux.HandleFunc("/v1/workspace/move", s.handleWorkspaceMove)
	mux.HandleFunc("/v1/workspace/todos", s.handleWorkspaceTodos)
	mux.HandleFunc("/v1/workspace/git/status", s.handleGitStatus)
	mux.HandleFunc("/v1/workspace/git/commit", s.handleGitCommit)
	mux.HandleFunc("/v1/workspace/git/realtime", s.handleGitRealtime)
	mux.HandleFunc("/v1/workspace/delete", s.handleWorkspaceDelete)
	mux.HandleFunc("/v1/worktrees", s.handleWorktrees)
	mux.HandleFunc("/v1/manage-worktree", s.handleManageWorktree)
}

func (s *Server) registerRuntimeRoutes(mux *http.ServeMux) {
	mux.HandleFunc("/v1/context/sources", s.handleContextSources)
	mux.HandleFunc("/v1/system/shutdown", s.handleSystemShutdown)
	mux.HandleFunc("/v1/permissions", s.handlePermissions)
	mux.HandleFunc("/v1/permissions/", s.handlePermissions)
	mux.HandleFunc("/v1/alerts", s.handleNotifications)
	mux.HandleFunc("/v1/alerts/", s.handleNotifications)
	mux.HandleFunc("/v1/alerts/summary", s.handleNotifications)
	mux.HandleFunc("/v1/notifications", s.handleNotifications)
	mux.HandleFunc("/v1/notifications/", s.handleNotifications)
	mux.HandleFunc("/v1/notifications/summary", s.handleNotifications)
	mux.HandleFunc(webPushRoutePrefix, s.handleWebPush)
	mux.HandleFunc(webPushRoutePrefix+"/", s.handleWebPush)
	mux.HandleFunc("/v1/update/status", s.handleUpdateStatus)
	mux.HandleFunc("/v1/update/apply", s.handleUpdateApply)
	mux.HandleFunc("/v1/update/run", s.handleUpdateRun)
	mux.HandleFunc("/v1/git/sync/inspect", s.handleGitSyncInspect)
	mux.HandleFunc("/v1/git/sync/apply", s.handleGitSyncApply)
	mux.HandleFunc(SessionStorageMaintenancePath, s.handleSessionStorageMaintenance)
	mux.HandleFunc("/v1/integrations", s.handleIntegrations)
	mux.HandleFunc("/v1/integrations/workspaces", s.handleIntegrationWorkspaces)
	mux.HandleFunc("/v1/integrations/workspaces/", s.handleIntegrationWorkspaceByID)
	mux.HandleFunc("/v1/integrations/builder/sessions", s.handleIntegrationBuilderSessions)
	mux.HandleFunc(V3RealtimeStreamPath, s.handleV3RealtimeStream)
	mux.HandleFunc(V3SyncBootstrapPath, s.handleSessionsV3SyncBootstrap)
	mux.HandleFunc(V3SyncHydratePath, s.handleSessionsV3SyncHydrate)
	mux.HandleFunc(V3SyncStreamPath, s.handleSessionsV3SyncStream)
	mux.HandleFunc("/v3/sessions:reconnect", s.handleSessionsV3Reconnect)
	mux.HandleFunc("/v3/sessions:discover", s.handleSessionsV3Discovery)
	mux.HandleFunc("/v3/sessions:search", s.handleSessionsV3Search)
	mux.HandleFunc("/v3/sessions:archive", s.handleSessionsV3Primary)
	mux.HandleFunc("/v3/sessions:delete", s.handleSessionsV3Delete)
	mux.HandleFunc(V3SyncLegacySessionsWorksetPath, s.handleSessionsV3Workset)
	mux.HandleFunc(V3SyncLegacyTUIWorksetPath, s.handleSessionsV3TUIWorkset)
	mux.HandleFunc("/v3/tui/sessions", s.handleSessionsV3TUI)
	mux.HandleFunc("/v3/tui/sessions/", s.handleSessionV3TUIByID)
	mux.HandleFunc("/v3/sessions", s.handleSessionsV3Primary)
	mux.HandleFunc("/v3/sessions/", s.handleSessionV3PrimaryByID)
	mux.HandleFunc("/v2/sessions", s.handleSessionsV2List)
	mux.HandleFunc("/v2/sessions/primary", s.handleSessionsV2Primary)
	mux.HandleFunc(runtimeSessionsV2OpenPath, s.handleRuntimeSessionsV2Open)
	mux.HandleFunc(runtimeSessionsV2Prefix, s.handleRuntimeSessionsV2ByID)
	mux.HandleFunc("/v2/sessions/", s.handlePrimarySessionV2ByID)
	mux.HandleFunc("/v1/sessions", s.handleSessions)
	mux.HandleFunc("/v1/sessions/", s.handleSessionByID)
}

