// Code generated by scripts/generate-session-connection-contract.mjs from contracts/session-connection.v1.schema.json; DO NOT EDIT.

package api

import "encoding/json"

const SessionConnectionContractVersion = 1
const SessionConnectionProtocol = "swarm.session-stream.v1"
const SessionConnectionDefaultReadyTimeoutMS = 10000

type RunPhase string

const (
	RunPhaseAccepted               RunPhase = "accepted"
	RunPhasePendingExecutor        RunPhase = "pending_executor"
	RunPhaseExecutorStarted        RunPhase = "executor_started"
	RunPhaseProviderRequestStarted RunPhase = "provider_request_started"
	RunPhaseProviderFirstEvent     RunPhase = "provider_first_event"
	RunPhaseOutputStreaming        RunPhase = "output_streaming"
	RunPhaseWaitingPermission      RunPhase = "waiting_permission"
	RunPhaseCompleted              RunPhase = "completed"
	RunPhaseFailed                 RunPhase = "failed"
	RunPhaseCancelled              RunPhase = "cancelled"
	RunPhaseInterrupted            RunPhase = "interrupted"
)

type SessionErrorAction struct {
	Method string `json:"method"`
	Path   string `json:"path"`
}

type SessionConnectionError struct {
	Code      string             `json:"code"`
	Message   string             `json:"message"`
	Retryable bool               `json:"retryable"`
	Action    SessionErrorAction `json:"action"`
}

type SessionConnectRequest struct {
	ClientId    string  `json:"client_id"`
	RequestId   string  `json:"request_id"`
	ResumeToken *string `json:"resume_token"`
}

type RunPhaseReason struct {
	Code      string `json:"code"`
	Message   string `json:"message"`
	Retryable bool   `json:"retryable,omitempty"`
}

type SessionCurrentRun struct {
	RunId  string          `json:"run_id"`
	Phase  RunPhase        `json:"phase"`
	Reason *RunPhaseReason `json:"reason,omitempty"`
}

type SessionSnapshot struct {
	EventSeq           uint64             `json:"event_seq"`
	Session            json.RawMessage    `json:"session"`
	Messages           []json.RawMessage  `json:"messages"`
	CurrentRun         *SessionCurrentRun `json:"current_run"`
	PendingPermissions []json.RawMessage  `json:"pending_permissions"`
	ActivePlan         *json.RawMessage   `json:"active_plan"`
	Usage              *json.RawMessage   `json:"usage"`
}

type SessionConnectionInfo struct {
	ConnectionId   string `json:"connection_id"`
	Transport      string `json:"transport"`
	Protocol       string `json:"protocol"`
	StreamUrl      string `json:"stream_url"`
	ResumeToken    string `json:"resume_token"`
	ReadyTimeoutMs uint64 `json:"ready_timeout_ms"`
}

type SessionConnectResponse struct {
	Ok              bool                  `json:"ok"`
	ContractVersion uint64                `json:"contract_version"`
	SessionId       string                `json:"session_id"`
	Snapshot        SessionSnapshot       `json:"snapshot"`
	Connection      SessionConnectionInfo `json:"connection"`
}

type SessionReadyFrame struct {
	Type         string `json:"type"`
	ConnectionId string `json:"connection_id"`
	SessionId    string `json:"session_id"`
	EventSeq     uint64 `json:"event_seq"`
	ResumeToken  string `json:"resume_token"`
}

type SessionEventFrame struct {
	Type        string          `json:"type"`
	SessionId   string          `json:"session_id"`
	EventSeq    uint64          `json:"event_seq"`
	Event       json.RawMessage `json:"event"`
	ResumeToken string          `json:"resume_token"`
}

type RunPhaseFrame struct {
	Type      string          `json:"type"`
	SessionId string          `json:"session_id"`
	RunId     string          `json:"run_id"`
	Phase     RunPhase        `json:"phase"`
	EventSeq  uint64          `json:"event_seq"`
	Reason    *RunPhaseReason `json:"reason,omitempty"`
}

type SessionReconnectRequiredReason string

const (
	SessionReconnectRequiredReasonResumeTokenExpired  SessionReconnectRequiredReason = "resume_token_expired"
	SessionReconnectRequiredReasonConnectionLeaseLost SessionReconnectRequiredReason = "connection_lease_lost"
	SessionReconnectRequiredReasonSessionDeleted      SessionReconnectRequiredReason = "session_deleted"
	SessionReconnectRequiredReasonAuthorizationLost   SessionReconnectRequiredReason = "authorization_lost"
	SessionReconnectRequiredReasonSlowConsumer        SessionReconnectRequiredReason = "slow_consumer"
)

type SessionReconnectRequiredFrame struct {
	Type      string             `json:"type"`
	SessionId string             `json:"session_id"`
	Reason    string             `json:"reason"`
	Action    SessionErrorAction `json:"action"`
}

type SessionStreamFrame interface {
	sessionStreamFrame()
}

func (SessionReadyFrame) sessionStreamFrame()             {}
func (SessionEventFrame) sessionStreamFrame()             {}
func (RunPhaseFrame) sessionStreamFrame()                 {}
func (SessionReconnectRequiredFrame) sessionStreamFrame() {}
