import test from 'node:test'
import assert from 'node:assert/strict'
import { readFile } from 'node:fs/promises'

async function readDesktopAppPage(): Promise<string> {
  return readFile(new URL('./desktop-app-page.tsx', import.meta.url), 'utf8')
}

test('routed new-chat activation only publishes a validated canonical result', async () => {
  const source = await readDesktopAppPage()
  const activationStart = source.indexOf('export async function activateDesktopV3RoutedSession')
  const activationEnd = source.indexOf('function desktopRunIntentFromV3', activationStart)
  const activation = source.slice(activationStart, activationEnd)

  assert.ok(activationStart >= 0 && activationEnd > activationStart)
  const normalizationStart = source.indexOf('function desktopV3RoutedResultResponse')
  const normalizationEnd = source.indexOf('function desktopV3RoutedSessionView', normalizationStart)
  const normalization = source.slice(normalizationStart, normalizationEnd)

  assert.ok(normalizationStart >= 0 && normalizationEnd > normalizationStart)
  assert.match(normalization, /normalizeDesktopV3RoutedSessionStartResponse\(result\)/)
  assert.match(activation, /const response = desktopV3RoutedResultResponse\(result\)/)
  assert.match(activation, /validateDesktopV3RoutedActivationResponse\(response\)/)
  assert.match(activation, /requireRealtimeController\(\)[\s\S]*ensureSessionConnected\(sessionId\)[\s\S]*structuredClone\(previousState\)[\s\S]*commitSnapshot\(previousState, nextState, \[\.\.\.actions\]\)/)
  assert.match(activation, /await onActivated\?\.\(response\)/)
  assert.match(activation, /deps\.getSnapshot\(\) === nextState[\s\S]*routedSessionSuffix[\s\S]*ownsRoute = shouldActivate\(\)[\s\S]*commitSnapshot\(nextState, previousState, \[\]\)[\s\S]*replaceURL\(previousURL\)/)
  assert.match(activation, /sessionCreateResponseToAction\(createResponse, sidebarScopeId\)/)
  assert.match(activation, /messageMutationResponseToAction\(messageResponse,[\s\S]*response\.first_message\.id\)/)
  assert.match(activation, /nextState\.sessionViewsById\[sessionId\] = routedView/)
  assert.match(activation, /nextState\.preferencesBySession\[sessionId\] = routedSettings\.effective_preference/)
  assert.match(activation, /nextState\.agentModelPolicyBySession\[sessionId\] = routedSettings\.agent_model_policy/)
  assert.match(activation, /selectSession\(sessionId\)/)
  assert.match(activation, /commitSnapshot\(previousState, nextState, \[\.\.\.actions\]\)/)
  assert.doesNotMatch(activation, /selectAndHydrateDesktopV3Session/)
})

test('routed activation derives URL identity from the returned source workspace and ignores stale completions', async () => {
  const source = await readDesktopAppPage()
  const handlerStart = source.indexOf('const handleRoutedSessionResolved = useCallback')
  const handlerEnd = source.indexOf('const handleArchivePlanSession', handlerStart)
  const handler = source.slice(handlerStart, handlerEnd)

  assert.ok(handlerStart >= 0 && handlerEnd > handlerStart)
  assert.match(handler, /source_workspace_path\.trim\(\)/)
  assert.match(handler, /returnedAuthority\.worktree_enabled[\s\S]*runtimeWorkspacePath === returnedAuthority\.worktree_root_path\?\.trim\(\)[\s\S]*runtimeWorkspacePath === expectedRuntimeWorkspacePath/)
  assert.match(handler, /!runtimeAuthorityMatches/)
  assert.doesNotMatch(handler, /returnedAuthority\.runtime_workspace_path\.trim\(\) !== authority\.runtime_workspace_path/)
  assert.match(handler, /source_workspace_id/)
  assert.match(handler, /unknown source workspace/)
  assert.match(handler, /activationGeneration === routedActivationGenerationRef\.current/)
  assert.match(handler, /routedActivationWorkspaceRef\.current === expectedWorkspacePath/)
  assert.match(source, /routedActivationGenerationRef\.current \+= 1|\+\+routedActivationGenerationRef\.current/)
  assert.match(handler, /await navigate\([\s\S]*params: \{ workspaceSlug, sessionId: response\.session_id \}/)
  assert.match(handler, /activationStillCurrent[\s\S]*throw new Error\('Routed Desktop activation is stale'\)/)
  assert.match(source, /onRoutedSessionResolved=\{handleRoutedSessionResolved\}/)
})

test('routed activation validates all returned display authority and never publishes before realtime readiness', async () => {
  const source = await readDesktopAppPage()
  const validationStart = source.indexOf('function validateDesktopV3RoutedActivationResponse')
  const validationEnd = source.indexOf('/**\n * Publishes one already-durable routed result', validationStart)
  const validation = source.slice(validationStart, validationEnd)
  const activationStart = source.indexOf('export async function activateDesktopV3RoutedSession')
  const activationEnd = source.indexOf('function desktopRunIntentFromV3', activationStart)
  const activation = source.slice(activationStart, activationEnd)

  assert.ok(validationStart >= 0 && validationEnd > validationStart)
  assert.match(validation, /desktopV3RoutedRequiredString\(identity\.title, 'session title'\) !== title/)
  assert.match(validation, /desktopV3RoutedRequiredString\(response\.session\.workspace_path, 'runtime workspace'\) !== runtimeWorkspacePath/)
  assert.match(validation, /desktopV3RoutedRequiredString\(response\.first_message\.content, 'first message'\)/)
  assert.match(validation, /settings\.mode !== response\.starting_mode/)
  assert.match(validation, /effectivePreference\?\.provider/)
  assert.match(validation, /effectivePreference\?\.model/)
  assert.match(validation, /mediaCapability\.capabilities/)
  assert.match(validation, /typeof identity\.worktree_enabled !== 'boolean'/)
  assert.match(validation, /identity\.requested_worktree_name/)
  assert.match(validation, /identity\.worktree_enabled/)
  assert.match(validation, /session\.worktree_root_path/)
  assert.match(validation, /session\.worktree_branch/)
  assert.ok(activation.indexOf('await controller.ensureSessionConnected(sessionId)') < activation.indexOf('deps.commitSnapshot(previousState, nextState'))
})

test('routed activation owns navigation rollback and suppresses stale failure toasts', async () => {
  const source = await readDesktopAppPage()
  const handlerStart = source.indexOf('const handleRoutedSessionResolved = useCallback')
  const handlerEnd = source.indexOf('const handleArchivePlanSession', handlerStart)
  const handler = source.slice(handlerStart, handlerEnd)

  assert.match(source, /const previousURL = deps\.currentURL\(\)/)
  assert.match(source, /const previousSelectedSessionId = previousState\.selectedSessionId/)
  assert.match(source, /const previousSidebarOrderByScope = structuredClone\(previousState\.sessionOrderByScope\)/)
  assert.match(source, /currentURL !== previousURL/)
  assert.match(source, /deps\.replaceURL\(previousURL\)/)
  assert.match(source, /window\.dispatchEvent\(new PopStateEvent\('popstate'/)
  assert.match(handler, /await activateDesktopV3RoutedSession\(/)
  assert.match(handler, /await navigate\(/)
  assert.match(handler, /if \(activationStillCurrent\(\)\)[\s\S]*setDesktopToast[\s\S]*throw error/)
  assert.doesNotMatch(handler, /void navigate\(/)
})

test('starting a new session requests focus for the pending composer', async () => {
  const source = await readDesktopAppPage()
  const handlerStart = source.indexOf('const handleStartNewSessionInWorkspace = useCallback')
  const handlerEnd = source.indexOf('const handleRoutedSessionResolved', handlerStart)
  const handler = source.slice(handlerStart, handlerEnd)

  assert.ok(handlerStart >= 0 && handlerEnd > handlerStart)
  assert.match(handler, /clearDesktopV3RoutedStartOperation\(\)/)
  assert.match(handler, /routedActivationGenerationRef\.current \+= 1/)
  assert.match(handler, /setNewSessionEpoch\(\(current\) => current \+ 1\)/)
  assert.match(handler, /dispatchDesktopV3Cache\(selectSession\(undefined\)\)/)
  assert.match(handler, /navigate\(\{ to: '\/\$workspaceSlug'/)
  assert.match(handler, /setComposerFocusSignal\(\(current\) => current \+ 1\)/)
  assert.match(source, /key=\{`new:\$\{routeWorkspace\.path\}:\$\{newSessionEpoch\}`\}/)
})

test('app-level new-chat wiring has no local pending authority or generic mode command', async () => {
  const source = await readDesktopAppPage()

  assert.doesNotMatch(source, /newSessionModeByWorkspace/)
  assert.doesNotMatch(source, /sessionModeCommand/)
  assert.doesNotMatch(source, /toggle-plan-auto/)
  assert.doesNotMatch(source, /DesktopV3RoutedNewSessionController/)
  assert.doesNotMatch(source, /createDesktopV3RoutedDraftState/)
  assert.doesNotMatch(source, /createDesktopV3RoutedStartOperation/)
  assert.doesNotMatch(source, /createDesktopV3CreateOnlySessionOperation|startDesktopV3CreateOnlySession/)
  assert.doesNotMatch(source, /titleToWorktreeBranchSlug|worktreeSessionBranch/)
  assert.match(source, /onRoutedSessionResolved=\{handleRoutedSessionResolved\}/)
  assert.doesNotMatch(source, /onRoutedSessionResolved:[\s\S]*as \{\}/)
})
