import { MediaDeliverable, OrchestratorMessage, ProjectSummary, RunningAutomation, RunningTask } from './orchestrate-types'

export const MOCK_PROJECTS: ProjectSummary[] = [
  {
    id: 'proj-swarm-platform',
    name: 'Swarm Platform',
    slug: 'swarm-platform',
    description: 'Local-first AI daemon, V3 session runtime & Desktop UI',
    repoPath: '~/swarm-go',
    branch: 'dev',
    gitStatus: 'clean',
    linkedWorkspaces: ['swarm-go', 'swarmcrit', 'work'],
    activeWorkersCount: 3,
    pendingDeliverablesCount: 4,
    runningTasksCount: 2,
  },
  {
    id: 'proj-social-studio',
    name: 'Social Media Studio',
    slug: 'social-studio',
    description: 'Multi-part AI video pipeline & automated social distributor',
    repoPath: '~/swarm-social',
    branch: 'main',
    gitStatus: 'clean',
    linkedWorkspaces: ['swarm-social'],
    activeWorkersCount: 2,
    pendingDeliverablesCount: 6,
    runningTasksCount: 1,
  },
  {
    id: 'proj-cloud-infra',
    name: 'Cloud Infra & Security',
    slug: 'cloud-infra',
    description: 'GCP Workload Identity Federation & dynamic lease brokers',
    repoPath: '~/swarmcrit',
    branch: 'dev',
    gitStatus: 'clean',
    linkedWorkspaces: ['swarmcrit'],
    activeWorkersCount: 1,
    pendingDeliverablesCount: 1,
    runningTasksCount: 0,
  },
]

export const MOCK_AUTOMATIONS: RunningAutomation[] = [
  {
    id: 'auto-video-gen',
    name: 'Social Video Batch Generator',
    kind: 'trigger',
    status: 'running',
    progressPercent: 60,
    currentStep: 'Rendering Part 6/10: "Neural Mesh Transformation"',
    lastRun: 'Just now',
    outputSummary: '4 videos rendered to canvas',
    totalRuns: 42,
  },
  {
    id: 'auto-nightly-testbench',
    name: 'Nightly Systemd-Nspawn Testbench',
    kind: 'cron',
    status: 'scheduled',
    nextRun: 'Tonight at 02:00 UTC (in 3h 15m)',
    lastRun: 'Yesterday (All 28 critical suites passed)',
    outputSummary: '100% test integrity',
    totalRuns: 184,
  },
  {
    id: 'auto-pr-reviewer',
    name: 'GitHub PR Coder Auto-Reviewer',
    kind: 'trigger',
    status: 'idle',
    lastRun: '1 hour ago',
    outputSummary: 'Approved PR #97: Fix composer slash popup',
    totalRuns: 56,
  },
  {
    id: 'auto-token-audit',
    name: 'Token Velocity & Bloat Monitor',
    kind: 'interval',
    status: 'running',
    progressPercent: 85,
    currentStep: 'Compacting session AGENTS.md injections',
    lastRun: '15m ago',
    outputSummary: 'Saved 12,400 tokens / prompt',
    totalRuns: 310,
  },
]

export const MOCK_DELIVERABLES: MediaDeliverable[] = [
  {
    id: 'deliv-vid-1',
    title: 'Neon Cyber Lattice (Part 1/10)',
    type: 'video',
    videoAspect: '9:16',
    duration: '0:15',
    status: 'ready',
    createdAt: '2 mins ago',
    author: 'Video Swarm Worker',
    prompt: 'Cinematic glowing cyber lattice pulsing with cyan neon nodes, 4k ultra-detailed volumetric lighting',
    metrics: { renderTime: '42s', tokens: '1.2k', views: 'Preview ready' },
  },
  {
    id: 'deliv-vid-2',
    title: 'Neural Core Genesis (Part 2/10)',
    type: 'video',
    videoAspect: '9:16',
    duration: '0:15',
    status: 'ready',
    createdAt: '4 mins ago',
    author: 'Video Swarm Worker',
    prompt: 'Floating obsidian cube radiating emerald energy filaments into atmospheric haze',
    metrics: { renderTime: '38s', tokens: '1.1k', views: 'Preview ready' },
  },
  {
    id: 'deliv-vid-3',
    title: 'Orbital Data Flow (Part 3/10)',
    type: 'video',
    videoAspect: '16:9',
    duration: '0:20',
    status: 'ready',
    createdAt: '7 mins ago',
    author: 'Video Swarm Worker',
    prompt: 'Orbital satellite relay receiving light-speed cryptographic signals above Earth horizon',
    metrics: { renderTime: '55s', tokens: '1.4k', views: 'Preview ready' },
  },
  {
    id: 'deliv-vid-4',
    title: 'Quantum Synapse (Part 4/10)',
    type: 'video',
    videoAspect: '9:16',
    duration: '0:15',
    status: 'generating',
    createdAt: 'Rendering now...',
    author: 'Video Swarm Worker',
    prompt: 'Microscopic view of bio-digital synapses sparking with gold and deep violet plasma',
    metrics: { renderTime: 'In progress', tokens: '1.3k' },
  },
  {
    id: 'deliv-code-1',
    title: 'feat: Lean Swarm Orchestrator agent harness',
    type: 'code',
    status: 'ready',
    createdAt: '12 mins ago',
    author: 'Coder Subagent',
    prompt: 'Register swarm-orchestrator in system_agent_registry.go and strip video/artifact bloat',
    metrics: { tokens: '2.8k' },
  },
  {
    id: 'deliv-report-1',
    title: 'Mission Control Token Velocity Report',
    type: 'report',
    status: 'accepted',
    createdAt: '30 mins ago',
    author: 'Finder Subagent',
    prompt: 'Token analysis across system prompts: 78% reduction by decoupling raw tool schemas',
    metrics: { tokens: '850' },
  },
]

export const MOCK_RUNNING_TASKS: RunningTask[] = [
  {
    id: 'task-101',
    title: 'Make 3 Social Media Videos for Feature Launch',
    agentType: 'designer',
    status: 'running',
    workspaceTarget: 'swarm-social',
    elapsed: '2m 15s',
    subtasks: [
      { id: 'st-1', title: 'Hydrate 3 prompt themes via Router', completed: true },
      { id: 'st-2', title: 'Batch dispatch to Video Generation Worker', completed: true },
      { id: 'st-3', title: 'Synthesize kinetic audio & visual transitions', completed: true },
    ],
    deliverables: [
      {
        id: 'deliv-vid-1',
        title: 'Neon Cyber Lattice (Part 1/3)',
        type: 'video',
        videoAspect: '9:16',
        duration: '0:15',
        status: 'ready',
        createdAt: '1m ago',
        author: 'Video Swarm Worker',
        prompt: 'Cinematic glowing cyber lattice pulsing with cyan neon nodes, 4k ultra-detailed volumetric lighting',
        metrics: { renderTime: '42s', tokens: '1.2k', views: 'Preview ready' },
      },
      {
        id: 'deliv-vid-2',
        title: 'Neural Core Genesis (Part 2/3)',
        type: 'video',
        videoAspect: '9:16',
        duration: '0:15',
        status: 'ready',
        createdAt: '2m ago',
        author: 'Video Swarm Worker',
        prompt: 'Floating obsidian cube radiating emerald energy filaments into atmospheric haze',
        metrics: { renderTime: '38s', tokens: '1.1k', views: 'Preview ready' },
      },
      {
        id: 'deliv-vid-3',
        title: 'Orbital Data Flow (Part 3/3)',
        type: 'video',
        videoAspect: '16:9',
        duration: '0:20',
        status: 'ready',
        createdAt: 'Just now',
        author: 'Video Swarm Worker',
        prompt: 'Orbital satellite relay receiving light-speed cryptographic signals above Earth horizon',
        metrics: { renderTime: '55s', tokens: '1.4k', views: 'Preview ready' },
      },
    ],
  },
  {
    id: 'task-102',
    title: 'Fix composer quick command popup trigger',
    agentType: 'coder',
    status: 'needs_review',
    workspaceTarget: 'swarm-go',
    elapsed: '1m 45s',
    subtasks: [
      { id: 'st-21', title: 'Locate slash command detection in composer.tsx', completed: true },
      { id: 'st-22', title: 'Fix keystroke event propagation', completed: true },
      { id: 'st-23', title: 'Pass keyboard navigation unit test', completed: true },
    ],
    diffPreview: `+ if (text.endsWith('/')) {\n+   setShowQuickCommands(true)\n+ }`,
    deliverables: [
      {
        id: 'deliv-code-1',
        title: 'PR #108: Fix composer quick command slash trigger & focus trap',
        type: 'code',
        status: 'ready',
        createdAt: '5m ago',
        author: 'Coder Subagent',
        prompt: 'Register slash command listener with keyboard navigation guards in composer.tsx',
        metrics: { tokens: '2.8k' },
      },
    ],
  },
  {
    id: 'task-103',
    title: 'Zero-Bloat Token Audit & Memory Invariants',
    agentType: 'finder',
    status: 'completed',
    workspaceTarget: 'swarm-go',
    elapsed: '45s',
    subtasks: [
      { id: 'st-31', title: 'Audit primary orchestrator prompt overhead', completed: true },
      { id: 'st-32', title: 'Verify isolated subagent AGENTS.md boundaries', completed: true },
    ],
    deliverables: [
      {
        id: 'deliv-report-1',
        title: 'Token Velocity & Memory Efficiency Audit Report',
        type: 'report',
        status: 'accepted',
        createdAt: '15m ago',
        author: 'Finder Subagent',
        prompt: 'Verified 78% prompt token reduction by scoping rules strictly to subagent worktrees',
        metrics: { tokens: '850' },
      },
    ],
  },
]

export const MOCK_CHAT_MESSAGES: OrchestratorMessage[] = [
  {
    id: 'msg-1',
    sender: 'user',
    text: 'Hey Swarm, make me 10 social media videos for our upcoming feature launch.',
    timestamp: '15:42',
  },
  {
    id: 'msg-2',
    sender: 'orchestrator',
    text: "On it! I've analyzed your project brief and dispatched the request to the Video Swarm Worker with 10 distinct high-energy themes (Cyber Lattice, Neural Genesis, Orbital Relay, etc.).\n\nI'm streaming the outputs directly to your Project Canvas. The first 3 clips are already rendered and ready for your review!",
    timestamp: '15:43',
    actionPills: [
      { label: 'Review Clip 1 (Neon Cyber)', action: 'preview-deliv-vid-1' },
      { label: 'View All 10 Render Slots', action: 'filter-videos' },
    ],
    linkedDeliverableIds: ['deliv-vid-1', 'deliv-vid-2', 'deliv-vid-3'],
  },
]
