import {
  MediaDeliverable,
  OrchestratorMessage,
  ProjectSummary,
  RunningAutomation,
  RunningTask,
} from './orchestrate-types'

export const MOCK_PROJECTS: ProjectSummary[] = [
  {
    id: 'proj-swarm-platform',
    name: 'Swarm Platform',
    slug: 'swarm-platform',
    description: 'Local-first AI daemon, V3 session runtime & Desktop UI',
    repoPath: '~/swarm-go',
    branch: 'dev',
    gitStatus: 'clean',
    linkedWorkspaces: ['swarm-go', 'swarmcrit', 'work'],
    activeWorkersCount: 3,
    pendingDeliverablesCount: 4,
    runningTasksCount: 2,
  },
  {
    id: 'proj-social-studio',
    name: 'Social Media Studio',
    slug: 'social-studio',
    description: 'Multi-part AI video pipeline & automated social distributor',
    repoPath: '~/swarm-social',
    branch: 'main',
    gitStatus: 'clean',
    linkedWorkspaces: ['swarm-social'],
    activeWorkersCount: 2,
    pendingDeliverablesCount: 6,
    runningTasksCount: 1,
  },
  {
    id: 'proj-cloud-infra',
    name: 'Cloud Infra & Security',
    slug: 'cloud-infra',
    description: 'GCP Workload Identity Federation & dynamic lease brokers',
    repoPath: '~/swarmcrit',
    branch: 'dev',
    gitStatus: 'clean',
    linkedWorkspaces: ['swarmcrit'],
    activeWorkersCount: 1,
    pendingDeliverablesCount: 1,
    runningTasksCount: 0,
  },
]

export const MOCK_AUTOMATIONS: RunningAutomation[] = [
  {
    id: 'auto-video-gen',
    name: 'Social Video Batch Generator',
    kind: 'trigger',
    status: 'running',
    progressPercent: 60,
    currentStep: 'Rendering 6/10',
    lastRun: 'just now',
    outputSummary: 'Rendering 6/10',
    totalRuns: 42,
  },
  {
    id: 'auto-nightly-testbench',
    name: 'Nightly Systemd-Nspawn Testbench',
    kind: 'cron',
    status: 'scheduled',
    nextRun: 'Scheduled for 02:00 In 3h 15m',
    lastRun: 'yesterday',
    outputSummary: 'Scheduled for 02:00 In 3h 15m',
    totalRuns: 184,
  },
  {
    id: 'auto-pr-reviewer',
    name: 'GitHub PR Coder Auto-Reviewer',
    kind: 'trigger',
    status: 'idle',
    lastRun: '1 hour ago',
    outputSummary: 'Idle',
    totalRuns: 56,
  },
  {
    id: 'auto-token-audit',
    name: 'Token Velocity & Bloat Monitor',
    kind: 'interval',
    status: 'running',
    progressPercent: 85,
    currentStep: 'Compacting session data',
    lastRun: '15m ago',
    outputSummary: 'Compacting session data',
    totalRuns: 310,
  },
]

export const MOCK_DELIVERABLES: MediaDeliverable[] = [
  {
    id: 'deliv-vid-1',
    title: 'Neon Cyber Lattice',
    type: 'video',
    thumbnailType: 'cyber_lattice',
    videoAspect: '16:9',
    duration: '0:15',
    status: 'ready',
    createdAt: '2 mins ago',
    author: 'Video Swarm Worker',
    prompt: 'Cinematic cyber lattice with neon nodes and volumetric lighting.',
    metrics: { renderTime: '42s', tokens: '1.2k', views: 'Preview ready' },
  },
  {
    id: 'deliv-vid-2',
    title: 'Neural Core Genesis',
    type: 'video',
    thumbnailType: 'neural_core',
    videoAspect: '16:9',
    duration: '0:15',
    status: 'ready',
    createdAt: '4 mins ago',
    author: 'Video Swarm Worker',
    prompt: 'Floating obsidian cube radiating energy into a digital haze.',
    metrics: { renderTime: '38s', tokens: '1.1k', views: 'Preview ready' },
  },
  {
    id: 'deliv-vid-3',
    title: 'Orbital Data Flow',
    type: 'video',
    thumbnailType: 'orbital_data',
    videoAspect: '16:9',
    duration: '0:20',
    status: 'ready',
    createdAt: '7 mins ago',
    author: 'Video Swarm Worker',
    prompt: 'Satellite relay with light-speed cryptographic signals.',
    metrics: { renderTime: '55s', tokens: '1.4k', views: 'Preview ready' },
  },
]

export const MOCK_RUNNING_TASKS: RunningTask[] = [
  {
    id: 'task-101',
    title: 'Make 3 Social Media Videos for Feature Launch',
    subtitle: 'Design → Generate → Polish → Deliver',
    agentType: 'designer',
    status: 'running',
    workspaceTarget: 'swarm-social',
    elapsed: '2m 15s',
    subtasks: [
      { id: 'st-1', title: 'Hydrate 3 prompt themes via Router', completed: true },
      { id: 'st-2', title: 'Batch dispatch to Video Generation Worker', completed: true },
      { id: 'st-3', title: 'Synthesize kinetic audio & visual transitions', completed: false },
    ],
    stepTimeline: [
      { step: 1, label: 'Themes', status: 'complete' },
      { step: 2, label: 'Generate', status: 'processing' },
      { step: 3, label: 'Edit', status: 'pending' },
      { step: 4, label: 'Deliver', status: 'pending' },
    ],
    deliverables: [
      {
        id: 'deliv-vid-1',
        title: 'Neon Cyber Lattice',
        type: 'video',
        thumbnailType: 'cyber_lattice',
        videoAspect: '16:9',
        duration: '0:15',
        status: 'ready',
        createdAt: '1m ago',
        author: 'Video Swarm Worker',
        prompt: 'Cinematic cyber lattice with neon nodes and volumetric lighting.',
        metrics: { renderTime: '42s', tokens: '1.2k', views: 'Preview ready' },
      },
      {
        id: 'deliv-vid-2',
        title: 'Neural Core Genesis',
        type: 'video',
        thumbnailType: 'neural_core',
        videoAspect: '16:9',
        duration: '0:15',
        status: 'ready',
        createdAt: '2m ago',
        author: 'Video Swarm Worker',
        prompt: 'Floating obsidian cube radiating energy into a digital haze.',
        metrics: { renderTime: '38s', tokens: '1.1k', views: 'Preview ready' },
      },
      {
        id: 'deliv-vid-3',
        title: 'Orbital Data Flow',
        type: 'video',
        thumbnailType: 'orbital_data',
        videoAspect: '16:9',
        duration: '0:20',
        status: 'ready',
        createdAt: 'Just now',
        author: 'Video Swarm Worker',
        prompt: 'Satellite relay with light-speed cryptographic signals.',
        metrics: { renderTime: '55s', tokens: '1.4k', views: 'Preview ready' },
      },
    ],
  },
  {
    id: 'task-102',
    title: 'Fix composer quick command popup trigger',
    subtitle: 'Update keybinding logic and event handling.',
    agentType: 'coder',
    status: 'needs_review',
    workspaceTarget: 'swarm-go',
    elapsed: '1m 45s',
    subtasks: [
      { id: 'st-21', title: 'Locate slash command detection in composer.tsx', completed: true },
      { id: 'st-22', title: 'Fix keystroke event propagation', completed: true },
      { id: 'st-23', title: 'Pass keyboard navigation unit test', completed: true },
    ],
    diffPreview: `- if (text.endsWith('/')) {\n+ if (text.endsWith('/')) {\n    setShowQuickCommands(true)\n  }`,
    diffLines: [
      { lineNum: 12, type: 'del', text: "if (text.endsWith('/')) {" },
      { lineNum: 13, type: 'add', text: "if (text.endsWith('/')) {" },
      { lineNum: 14, type: 'normal', text: '    setShowQuickCommands(true)' },
      { lineNum: 15, type: 'normal', text: '  }' },
    ],
    deliverables: [
      {
        id: 'deliv-code-1',
        title: 'PR #108: Fix composer quick command slash trigger & focus trap',
        type: 'code',
        status: 'ready',
        createdAt: '5m ago',
        author: 'Coder Subagent',
        prompt: 'Register slash command listener with keyboard navigation guards in composer.tsx',
        metrics: { tokens: '2.8k' },
      },
    ],
  },
]

export const MOCK_CHAT_MESSAGES: OrchestratorMessage[] = [
  {
    id: 'msg-1',
    sender: 'user',
    text: 'Hey Swarm, make me 10 social media videos for our upcoming feature launch.',
    timestamp: '3:42 PM',
  },
  {
    id: 'msg-2',
    sender: 'orchestrator',
    text: "I've analyzed your project brief and created a video generation workflow. I'll use high-energy themes with cyber lattice, neural genesis, and orbital relay aesthetics.\n\n3 videos are currently rendering and will be ready shortly.",
    timestamp: '3:43 PM',
    videoProgressCard: {
      title: 'Video generation in progress...',
      progressPercent: 60,
      clipsLabel: '6/10 clips',
      aspect: '16:9',
    },
  },
  {
    id: 'msg-3',
    sender: 'orchestrator',
    text: 'Your first 3 videos are ready! They follow your feature launch theme and are optimized for social media.\n\nWould you like me to proceed with the remaining 7 variations, or make any adjustments?',
    timestamp: '3:45 PM',
    actionButton: {
      label: 'Preview all 3 videos',
      action: 'preview_all_videos',
    },
    linkedDeliverableIds: ['deliv-vid-1', 'deliv-vid-2', 'deliv-vid-3'],
  },
]
