package tool

// AutomationV2AuthoringInstructions is shared by the provider schema and harness.
const AutomationV2AuthoringInstructions = `Automation V2 uses the canonical executable plan document with automation_v2, never an ordinary plan merely titled hourly. From a fresh conversation submit the complete document using exit_plan_mode in Plan or plan_manage action=request_new_plan in Auto. No existing plan, automation, save, approval or grant is required. This stores only a pending Automation plan review; stop authoring and let the user explicitly Accept automation. Acceptance creates and activates the disclosed schedule; the first run follows that schedule, not immediate one-shot execution. Never approve or activate your own proposal. Preserve exact instructions and cadence. Intervals are elapsed seconds (60–31622400); cron has five numeric, * or */n fields and requires an explicit IANA timezone. No ranges, lists, names or simultaneous restricted day-of-month/day-of-week. Ask about missing wall-clock time/timezone or genuinely ambiguous timing; never approximate unsupported cadence. If expiration was unspecified use {"kind":"indefinite"}; only requested finite expiration uses {"kind":"at","expires_at":<future Unix milliseconds>}. Read manage_automation review for the current exact review before editing; resubmit the complete document with automation_review unchanged, preserving unrelated instructions/settings. Edits remain pending and do not alter active execution. Do not invent IDs or turn a recurring review into one-shot approval.
Complete fresh Auto example: {"action":"request_new_plan","document":{"title":"Automation plan: hourly repository report","info":{"goal":"Report repository status without modifying files"},"automation_v2":{"schema_version":2,"schedule":{"kind":"interval","interval_seconds":3600},"missed":"skip","overlap":"serialize","activate_on_accept":true,"expiration":{"kind":"indefinite"}},"checkpoints":[{"id":"report","title":"Report repository status","status":"pending","order":1,"tasks":["Inspect repository status and report changes; do not modify files"],"acceptance_criteria":["A factual status report is returned"]}]}}. In Plan use the same document with exit_plan_mode, omitting action. Daily 18:00 UTC instead uses schedule={"kind":"cron","cron":"0 18 * * *","timezone":"UTC"}.`

func sessionPlanAutomationV2ToolSchema() map[string]any {
	str := func(values ...string) map[string]any { return map[string]any{"type": "string", "enum": values} }
	return map[string]any{"type": "object", "additionalProperties": false, "required": []string{"schema_version", "schedule", "missed", "overlap", "activate_on_accept"}, "description": AutomationV2AuthoringInstructions, "properties": map[string]any{
		"schema_version": map[string]any{"type": "integer", "enum": []int{2}},
		"schedule":       map[string]any{"type": "object", "additionalProperties": false, "required": []string{"kind"}, "properties": map[string]any{"kind": str("interval", "cron"), "interval_seconds": map[string]any{"type": "integer", "minimum": 60, "maximum": 31622400}, "cron": map[string]any{"type": "string"}, "timezone": map[string]any{"type": "string"}}},
		"missed":         str("skip", "coalesce"), "overlap": str("serialize", "independent"), "activate_on_accept": map[string]any{"type": "boolean", "enum": []bool{true}},
		"expiration": map[string]any{"type": "object", "additionalProperties": false, "required": []string{"kind"}, "properties": map[string]any{"kind": str("indefinite", "at"), "expires_at": map[string]any{"type": "integer", "minimum": 1}}},
	}}
}
func automationV2ReviewSchema() map[string]any {
	return map[string]any{"type": "object", "additionalProperties": false, "required": []string{"proposal_id", "revision", "digest"}, "properties": map[string]any{"proposal_id": map[string]any{"type": "string"}, "revision": map[string]any{"type": "integer", "minimum": 1}, "digest": map[string]any{"type": "string"}}}
}
func manageAutomationV2Definition() Definition {
	return Definition{Type: "function", Name: "manage_automation", Description: AutomationV2AuthoringInstructions + " This tool only reads V2 review/context, progress with explicit display timezone, or bounded accepted records in the current workspace. Mutations use the plan review workflow; V1 save/approve/enable/run are retired.", Parameters: map[string]any{"type": "object", "additionalProperties": false, "required": []string{"action"}, "properties": map[string]any{"action": map[string]any{"type": "string", "enum": []string{"review", "context", "list", "progress"}}, "cursor": map[string]any{"type": "string"}, "timezone": map[string]any{"type": "string"}, "limit": map[string]any{"type": "integer", "minimum": 1, "maximum": 50}}}}
}
