import { useEffect, useState } from 'react'
import './memory-page.css'
import { requestJson } from '../../../app/api'

type Entry = { id: string; kind: string; content: string; workspace_id?: string; session_id?: string; pinned: boolean; revision?: number; sources?: unknown[] }
type Settings = Record<string, boolean | number | string | string[] | null>
type Change = { revision: number; entry_id: string; operation: string; timestamp: number; actor: unknown; reason: string; before?: Entry; after?: Entry; redacted: boolean; settings_before?: Settings; settings_after?: Settings }
type Job = { id: string; status: string; error?: string; proposal?: Entry }
type Document = { revision: number; entries: Entry[] | null; settings: Settings; stored_tokens: number; token_method: string; history: Change[] | null; jobs?: Job[] }
const blank: Entry = { id: '', kind: 'rule', content: '', pinned: false }

export function MemoryPage() {
 const [doc,setDoc]=useState<Document>(); const [entry,setEntry]=useState<Entry>(blank); const [settings,setSettings]=useState<Settings>({}); const [reason,setReason]=useState(''); const [error,setError]=useState(''); const [busy,setBusy]=useState(false); const [session,setSession]=useState(''); const [preview,setPreview]=useState<unknown>();
 const load=async()=>{ const d=await requestJson<Document>('/v1/memory'); setDoc(d);setSettings(d.settings) }
 useEffect(()=>{void load().catch(e=>setError(String(e)))},[])
 const mutate=async(body: Record<string,unknown>)=>{setBusy(true);setError('');try{await requestJson('/v1/memory',{method:'POST',headers:{'Content-Type':'application/json'},body:JSON.stringify({expected_revision:doc?.revision,reason,...body})},true,150000);await load();setPreview(undefined)}catch(e){setError(`${String(e)}. Your draft is preserved. Refresh before retrying a stale save.`)}finally{setBusy(false)}}
 return <main className="memory-page">
  <nav><a href="/">Workspaces</a> · <a href="/settings">Settings</a></nav><h1 className="text-2xl font-semibold">Memory</h1>
  <p>Contextual guidance, not permission. Explicit rules, workspace orientation and learned context remain distinct. Automation cannot rewrite pinned rules.</p>
  {error && <p role="alert">{error}</p>}
  <button onClick={()=>void load().catch(e=>setError(String(e)))}>Refresh stored state (replaces settings draft)</button>
  {!doc ? <p role="status">Loading memory…</p> : <>
   <p>Revision {doc.revision} · Stored {doc.stored_tokens} / {String(doc.settings.storage_tokens)} · Injection budget {String(doc.settings.injection_tokens)}. Accounting: {doc.token_method} — conservative UTF-8 byte upper bound, not a model tokenizer. Stored counts cover content; injection includes serialized metadata.</p>
   <section aria-label="Stored entries"><h2>Stored entries</h2>{(doc.entries??[]).map(e=><article key={e.id} className="my-3 rounded border p-3"><h3>{e.id} · {e.kind}{e.pinned?' · pinned':''}</h3><p>Workspace: {e.workspace_id||'account'} · Session: {e.session_id||'all'} · Revision {e.revision}</p><pre className="whitespace-pre-wrap break-words">{e.content}</pre><details><summary>Provenance</summary><pre className="whitespace-pre-wrap">{JSON.stringify(e.sources??[],null,2)}</pre></details><button disabled={busy} onClick={()=>setEntry({...e,sources:undefined})}>Edit</button> <button disabled={busy||!reason.trim()} onClick={()=>{if(window.confirm('Permanently forget this entry and redact its history? This cannot be restored.'))void mutate({action:'forget',entry_id:e.id})}}>Forget permanently</button></article>)}</section>
   <section aria-label="Memory editor"><h2>Explicit memory editor</h2><p>Editing learned content is an explicit user revision, not automated provenance.</p><label>ID <input value={entry.id} onChange={e=>setEntry({...entry,id:e.target.value})}/></label><label>Kind <select value={entry.kind} onChange={e=>setEntry({...entry,kind:e.target.value})}><option>rule</option><option>orientation</option><option>learned</option></select></label><label>Workspace ID <input value={entry.workspace_id??''} onChange={e=>setEntry({...entry,workspace_id:e.target.value})}/></label><label>Session ID <input value={entry.session_id??''} onChange={e=>setEntry({...entry,session_id:e.target.value})}/></label><label><input type="checkbox" checked={entry.pinned} onChange={e=>setEntry({...entry,pinned:e.target.checked})}/>Pinned</label><label>Content<textarea aria-label="Content" className="block w-full" rows={8} value={entry.content} onChange={e=>setEntry({...entry,content:e.target.value})}/></label><label>Reason for change<input value={reason} onChange={e=>setReason(e.target.value)}/></label><button disabled={busy||!reason.trim()||!entry.id||!entry.content} onClick={()=>void mutate({action:'remember',entry})}>Save explicit memory</button><button onClick={()=>setEntry(blank)}>New entry</button></section>
   <section aria-label="Memory settings"><h2>Scope, automation and budgets</h2><p>Automation is opt-in. Manual mode never schedules recurring reads. Exclusions permanently forget source-derived content and history; removing an exclusion does not erase its tombstone.</p>{Object.entries(settings).filter(([key])=>key!=='automation_user_id').map(([key,value])=><label key={key} className="my-2 block">{key.replace(/_/g,' ')} {typeof value==='boolean'?<input type="checkbox" checked={value} onChange={e=>setSettings({...settings,[key]:e.target.checked})}/>:key==='mode'?<select value={String(value)} onChange={e=>setSettings({...settings,[key]:e.target.value})}><option value="manual">Manual only</option><option value="recurring">Recurring</option></select>:<input type={typeof value==='number'?'number':'text'} value={Array.isArray(value)?value.join(', '):value??''} onChange={e=>setSettings({...settings,[key]:typeof value==='number'?Number(e.target.value):Array.isArray(value)||key.includes('workspaces')||key.includes('sessions')?e.target.value.split(',').map(x=>x.trim()).filter(Boolean):e.target.value})}/>}</label>)}<p>Scope lists use comma-separated workspace/session IDs. Spend limits are microunits of USD.</p><button disabled={busy} onClick={()=>{if(window.confirm('Apply settings? New exclusions permanently redact affected memory.'))void mutate({action:'settings',settings})}}>Save settings</button><button disabled={busy} onClick={()=>void mutate({action:'settings',settings:{...doc.settings,automation_enabled:false}})}>Pause automation</button></section>
   <section aria-label="Memory jobs"><h2>Jobs and review queue</h2><button disabled={busy} onClick={()=>void mutate({action:'run_now',job_id:crypto.randomUUID()})}>Run now</button><p>Refresh to inspect progress. No background polling. Cancel remains available during a request.</p>{(doc.jobs??[]).map(j=><article key={j.id}><h3>{j.id} · {j.status}</h3><pre className="whitespace-pre-wrap break-words">{JSON.stringify(j,null,2)}</pre>{['queued','running','review'].includes(j.status)&&<button onClick={()=>void mutate({action:'cancel',job_id:j.id})}>Cancel / reject</button>}{j.status==='review'&&<button disabled={busy} onClick={()=>void mutate({action:'approve',job_id:j.id})}>Approve proposed change</button>}</article>)}</section>
   <section aria-label="Session injection"><h2>Next-request memory preview</h2><p>This previews current selection, not historical provider input. Rules precede orientation and learned context; omitted entries remain stored.</p><label>Session ID (empty for account-only)<input value={session} onChange={e=>setSession(e.target.value)}/></label><button onClick={()=>void requestJson('/v1/memory?session_id='+encodeURIComponent(session)).then(setPreview).catch(e=>setError(String(e)))}>Inspect injection and omissions</button><pre className="whitespace-pre-wrap break-words">{preview?JSON.stringify(preview,null,2):''}</pre></section>
   <section aria-label="Memory history"><h2>Diff and history</h2>{(doc.history??[]).slice().reverse().map(h=><details key={h.revision}><summary>Revision {h.revision} · {h.operation} · {new Date(h.timestamp).toLocaleString()} · {h.reason}</summary><pre className="whitespace-pre-wrap break-words">{JSON.stringify(h,null,2)}</pre>{!h.redacted&&h.after&&<button disabled={busy||!reason.trim()} onClick={()=>void mutate({action:'restore',entry_id:h.entry_id,restore_revision:h.revision})}>Restore as a new revision</button>}</details>)}</section>
  </>}
 </main>
}
