import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

const pageSourceUrl = new URL('./video-tool-page.tsx', import.meta.url)
const routerSourceUrl = new URL('../../../../app/router.tsx', import.meta.url)
const desktopPageSourceUrl = new URL('../../layout/desktop-app-page.tsx', import.meta.url)

test('Video Studio fills the app surface without an inset page wrapper', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')

  assert.match(source, /<div className="absolute inset-0 flex min-h-0 flex-col overflow-hidden/)
  assert.match(source, /<main className="flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain lg:flex-row lg:overflow-hidden">/)
  assert.match(source, /lg:hidden/)
  assert.doesNotMatch(source, /Coming soon for mobile/)
  assert.doesNotMatch(source, /mx-auto hidden h-full w-full max-w-none flex-col px-4 py-4/)
})

test('Video Studio tolerates legacy nullable timeline clip arrays', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  assert.match(source, /currentRevision\?\.timeline\.clips\?\.some/)
  assert.match(source, /\(currentRevision\.timeline\.clips \?\? \[\]\)\.filter/)
})

test('Video Studio reviews nested selective iterations in the sidebar and keeps the center player review-free', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const proposalSource = await readFile(new URL('../video-studio/video-studio-surface.tsx', import.meta.url), 'utf8')

  assert.match(source, /replaceCachedVideoMedia/)
  assert.match(source, /replaceCachedImageMedia/)
  assert.match(source, /<VideoIterationSidebar/)
  assert.match(source, /layoutClassName="flex max-h-\[42dvh\]/)
  assert.match(source, /lg:w-\[220px\]/)
  assert.match(source, /childrenClassName="mt-3 min-h-0 flex-1 overflow-y-auto"/)
  assert.match(source, /compactSelectedSession=\{Boolean\(selectedThread && !selectedLibraryVideo\)\}/)
  assert.match(source, />Video workspace<\/p>/)
  assert.doesNotMatch(source, />Current movie<\/p>/)
  assert.match(source, /Previewing r\{previewRevision\.revision_number\}/)
  assert.match(source, /Restore as new version/)
  assert.match(source, /videoProjectProjectionSequence/)
  assert.match(source, /selectionKind: 'iteration'/)
  assert.match(source, /iterationContext=\{studioComposerContext\?\.iteration\}/)
  assert.match(source, /VIDEO_STUDIO_UI_PLAYHEAD_INTERVAL_MS/)
  assert.match(source, /now - lastPublishedPlayheadRef\.current >= VIDEO_STUDIO_UI_PLAYHEAD_INTERVAL_MS/)
  assert.match(source, /routeOptions=\{studioRouteOptions\}/)
  assert.match(source, /playheadMs=\{studioSidecarPlayheadMs\}/)
  assert.match(proposalSource, /memo\(function VideoIterationSidebar/)
  assert.match(proposalSource, /memo\(function VideoSessionAISidecar/)
  assert.match(source, /onMessageSent=\{handleStudioMessageSent\}/)
  assert.match(source, /aria-label="Pending turn review"/)
  assert.match(source, /data-video-focused-review-scroll/)
  assert.match(source, /overflow-y-auto overscroll-contain/)
  assert.match(source, /New pending confirmation · r/)
  assert.match(source, /Review pending clips/)
  assert.match(source, /focusedReviewParts\.map/)
  assert.match(source, /Play in main player \+ soundtrack/)
  assert.match(source, /selectedCandidateID \? 'Switch' : 'Lock'/)
  assert.match(source, /focusedReviewLockedParts\.length/)
  assert.match(source, /Still base \+ \$\{composedVideoCount\} composed video slot/)
  assert.match(source, /Composed playback/)
  assert.match(source, />Continue with AI<\/Button>/)
  assert.match(source, /Keep the proposal pending for my explicit confirmation; do not accept it or render the video/)
  assert.match(source, /Confirm all \$\{currentWorkingVisualLayout\.length\} clips/)
  assert.match(source, /Choose HTML motion first/)
  assert.match(source, /aria-label="Pending video confirmation"/)
  assert.match(source, /beginTimelinePlayback\(layoutSegment\.timelineStart\)/)
  assert.match(source, /beginTimelinePlayback\(segment\.timelineStart\)/)
  assert.match(source, /Pending changes are not final/)
  assert.match(source, /Confirm pending changes to render/)
  assert.match(source, /renderBlockedByPendingProposal/)
  assert.match(source, /Storyboard placeholder · filming needed/)
  assert.match(source, /Replace \$\{pendingStoryboardPartIDs\.length\} storyboard placeholder/)
  assert.match(proposalSource, /video_storyboard_capture_state_id/)
  assert.match(proposalSource, /video_storyboard_source/)
  assert.match(proposalSource, /video_storyboard_still/)
  assert.match(source, /Previous revision/)
  assert.doesNotMatch(source, /choose an iteration/)
  assert.doesNotMatch(source, /Choose and attach to Swarm/)
  assert.doesNotMatch(proposalSource, /activityKeyRef/)
  assert.doesNotMatch(proposalSource, /renderedMessages\.liveRuns\.map\(\(run\)/)
  assert.doesNotMatch(source, /onActivity=\{handleStudioActivity\}/)
  assert.doesNotMatch(source, /<VideoProposalReview/)
  assert.doesNotMatch(source, /aria-label="Kept video plan"/)

  assert.match(proposalSource, /aria-label="Video iterations"/)
  assert.match(proposalSource, /buildVideoIterationTimeline/)
  assert.match(proposalSource, /selectedIteration\?\.proposal\?\.status === 'pending' && selectedIteration\.id === newestPendingIterationId/)
  assert.match(proposalSource, /setPreviewId\(newestPendingIterationId\)/)
  assert.match(proposalSource, /proposal\.accepted_operation_ids/)
  assert.match(proposalSource, /Enable \$\{change\.label\}/)
  assert.match(proposalSource, /props\.onFocusChange\(change\.clipId, change\.startMs\)/)
  assert.match(proposalSource, /Attach \$\{change\.label\} to AI composer/)
  assert.match(proposalSource, /Confirm enabled changes/)
  assert.match(proposalSource, /selectedOperationIds: enabledIds/)
  assert.match(proposalSource, /video_iteration_parent_revision_id/)
  assert.match(proposalSource, /video_iteration_candidate_revision_id/)
  assert.match(proposalSource, /video_iteration_change_id/)
  assert.match(proposalSource, /video_iteration_range_start_ms/)
  assert.match(proposalSource, /video_iteration_range_end_ms/)
})

test('Video Studio pins one clip-owned animation selection surface and an identity-led exact-aspect player', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const proposalSource = await readFile(new URL('../video-studio/video-studio-surface.tsx', import.meta.url), 'utf8')

  assert.match(source, /className="relative w-full shrink-0 overflow-hidden[^"]*" data-video-studio-player-viewport style=\{\{ aspectRatio:/)
  assert.match(source, /width=\{\(shadowTimeline \?\? playerRevision\?\.timeline\)\?\.width \?\? 1920\}/)
  assert.match(source, /height=\{\(shadowTimeline \?\? playerRevision\?\.timeline\)\?\.height \?\? 1080\}/)
  assert.match(source, /<canvas[^>]*className="absolute inset-0 h-full w-full bg-black object-contain"/)
  assert.match(source, /<div className="absolute inset-0 overflow-hidden bg-black"><iframe[^>]*data-video-studio-live-animation/)
  assert.doesNotMatch(source, /sm:min-h-\[360px\]|lg:min-h-\[480px\]|style=\{\{ maxHeight: '100%' \}\}/)
  assert.match(source, /data-video-studio-live-animation/)
  assert.match(source, /title=\{activeCandidate\?\.label \|\| liveAnimationPart\.title\}/)
  assert.match(source, /Play in main player \+ soundtrack/)
  assert.match(source, /videoActivePreviewIdentity/)
  assert.match(source, /animationSelectionRequestSequenceRef/)
  assert.match(source, /The still fallback is not substituted for the selected motion source/)
  assert.match(source, /shouldScheduleVideoCanvasFrame\(isPlaying, document\.visibilityState\)/)
  assert.match(source, /document\.addEventListener\('visibilitychange', handleVisibilityChange\)/)
  assert.match(source, /entry\.element\.addEventListener\('load', requestCanvasRender\)/)
  assert.doesNotMatch(source, /iterationCardURLs|Preview variants for \{currentIterationPart\.title\}/)
  assert.doesNotMatch(source, /aria-label=\{`\$\{planPart\.title\} animation sources`}\>/)
  assert.match(source, /This variant does not belong to \$\{part\.title\}\./)
  assert.match(source, /focusedVideoReviewPartLocked/)
  assert.match(source, /Choose a variant/)
  assert.doesNotMatch(source, /MP4 promotion|MP4 export required|promoted motion derivative/)
  assert.doesNotMatch(proposalSource, /exact MP4 derivative is promoted|animation-derivative-promote/)
  assert.match(proposalSource, /The selected canonical source can be confirmed directly/)

  const selectionCalls = source.match(/selectLiveAnimationCandidate\(part, candidate\)/g) ?? []
  assert.equal(selectionCalls.length, 1, 'candidate persistence must have one clip-card control; preview and source navigation must not duplicate selection')
  assert.doesNotMatch(source, /animation sources`}>[\s\S]*selectLiveAnimationCandidate\(planPart, candidate\)/)
})

test('Video Studio places the timeline directly below the player before clip review cards', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const playerIndex = source.indexOf('aria-label="Video player and timeline"')
  const timelineIndex = source.indexOf('aria-label="Video timeline"')
  const clipReviewIndex = source.indexOf('aria-label="Pending turn review"')

  assert.ok(playerIndex >= 0)
  assert.ok(timelineIndex > playerIndex)
  assert.ok(clipReviewIndex >= 0)
  assert.ok(clipReviewIndex < playerIndex)
  assert.match(source.slice(timelineIndex - 80, timelineIndex + 80), /order-1/)
  assert.match(source.slice(clipReviewIndex - 120, clipReviewIndex + 120), /aria-label="Pending turn review"/)
})

test('Video Studio exposes exact-aspect pending spatial composition controls', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const compositionSource = await readFile(new URL('../video-studio/video-composition.tsx', import.meta.url), 'utf8')
  assert.match(source, /<VideoCompositionOverlay/)
  assert.match(source, /<VideoCompositionEditor/)
  assert.match(source, /proposeCompositionChange/)
  assert.match(source, /Linked layout/)
  assert.match(compositionSource, /Apply to linked shots/)
  assert.match(compositionSource, /Detach shot/)
  assert.match(compositionSource, /Relink/)
  assert.match(compositionSource, /Composition source/)
  assert.match(compositionSource, /Composition fit/)
  assert.match(compositionSource, /Composition mask/)
  assert.match(compositionSource, /Composition audio/)
  assert.match(compositionSource, /video\.addEventListener\('loadedmetadata', seek, \{ once: true \}\)/)
  assert.match(compositionSource, /All changes create or update a pending proposal/)
})

test('Video Studio submits selectable durable renders and exposes a resilient project render center', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const renderCenterSource = await readFile(new URL('../video-studio/video-render-center.tsx', import.meta.url), 'utf8')

  assert.match(source, /aria-label="Render quality settings"/)
  assert.match(source, /VIDEO_RENDER_PRESETS\.map/)
  assert.match(source, /quality: preset\.quality, quality_preset: preset\.id, fps: preset\.fps/)
  assert.match(source, /listVideoRenderJobs\(selectedThread\.id, videoProject\.id\)/)
  assert.match(source, /window\.setInterval\(\(\) => \{ void refreshRenderJobs\(false\) \}, 2_000\)/)
  assert.match(renderCenterSource, /Existing jobs are retained and polling will retry automatically/)
  assert.doesNotMatch(source, /catch \{[\s\S]{0,100}clearInterval\(pollInterval\)/)
  assert.match(renderCenterSource, /aria-label="Video renders"/)
  assert.match(renderCenterSource, /Durable render queue/)
  assert.match(renderCenterSource, /queued'[\s\S]*'rendering'[\s\S]*'ready'[\s\S]*'failed'[\s\S]*'cancelled'/)
  assert.match(renderCenterSource, /videoRenderRemainingMs/)
  assert.match(renderCenterSource, /props\.onCancel\(job\)/)
  assert.match(renderCenterSource, /Multiple renders may run concurrently/)
})

test('Video Studio exposes only the implemented soundtrack contract and an explicit audio lane', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const proposalSource = await readFile(new URL('../video-studio/video-studio-surface.tsx', import.meta.url), 'utf8')

  assert.match(source, /aria-label="Soundtrack controls"/)
  assert.match(source, /aria-label="Soundtrack lane"/)
  assert.match(source, /aria-label="Choose trusted soundtrack"/)
  assert.match(source, /Playing pending working audio/)
  assert.match(source, /No soundtrack in this player revision/)
  assert.match(source, /syncTimelineAudioPlayback\(timelineLayout, audioElementsRef\.current, startAt, true\)/)
  assert.match(source, /syncTimelineAudioPlayback\(timelineLayout, audioElementsRef\.current, nextPlayhead, isPlaying\)/)
  assert.doesNotMatch(source, /workingSoundtrack\?\.name/)
  assert.match(source, /source_kind: 'source_audio'/)
  assert.match(source, /Propose placement \/ trim \/ volume change/)
  assert.match(proposalSource, /'replace_clip'/)
  assert.doesNotMatch(source, /Waveform|Fade in|Fade out|Loop soundtrack|Duck narration|Beat sync/)
})

test('Video Studio keeps sessions and standalone retained videos as separate navigation surfaces', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  assert.match(source, /const videoLibraryNavigation = \([\s\S]*aria-label="Standalone video library"/)
  assert.match(source, /placeholder="Filter videos or related sessions"/)
  assert.match(source, /aria-label="Selected library video"/)
  assert.match(source, /aria-label="Selected video iteration"/)
  assert.match(source, /Videos in this session/)
  assert.match(source, /sessionsLabel="Video sessions"[\s\S]*beforeSessions=\{videoLibraryNavigation\}/)
  assert.match(source, /Start new session with r\{selectedLibraryRevision\?\.revision_number \?\? 0\} attached/)
  assert.match(source, /attachToSession: true/)
  assert.match(source, /fetchWorkspaceVideoCatalog\(selectedWorkspacePath\)/)
  assert.match(source, /Start new session with r\{selectedLibraryRevision\?\.revision_number \?\? 0\} attached/)
  assert.match(source, /source_video_revision_id/)
  assert.match(source, /source_archived/)
  assert.doesNotMatch(source, /sessionsLabel="Videos"/)
})

test('Video Studio keeps a route-backed video selection and exposes session mode', async () => {
  const [source, routerSource, desktopSource] = await Promise.all([
    readFile(pageSourceUrl, 'utf8'),
    readFile(routerSourceUrl, 'utf8'),
    readFile(desktopPageSourceUrl, 'utf8'),
  ])

  assert.match(routerSource, /path: '\/\$workspaceSlug\/studio\/\$videoSessionId'/)
  assert.match(source, /VIDEO_STUDIO_LAST_SESSION_STORAGE_KEY/)
  assert.match(source, /to: '\/\$workspaceSlug\/studio\/\$videoSessionId'/)
  assert.match(source, /to: '\/\$workspaceSlug\/\$sessionId'/)
  assert.match(source, /label: 'Open session mode'/)
  assert.match(source, /data-testid="video-studio-session-toggle"/)
  assert.match(source, /aria-label="Switch to session mode"/)
  assert.match(desktopSource, />Video sessions</)
  assert.match(desktopSource, /childLabel=""/)
  assert.match(desktopSource, /selectionGroup="video"/)
  assert.match(desktopSource, /archiveDesktopV3Sessions\(ids\)/)
  assert.doesNotMatch(desktopSource, /routeSessionIsVideoStudio \|\| videoStudioRoute/)
  assert.match(desktopSource, /routeSessionHasVideoProject = routeSessionIsVideoStudio \|\| routeSessionVideoProjectQuery\.data === true/)
  assert.match(desktopSource, /sessionVideoProjectPresenceKey\(routeSessionId, routeSessionVideoProjectSequence\)/)
  assert.match(desktopSource, /studioMode=\{routeSessionHasVideoProject \? 'session' : null\}/)
  assert.match(source, /videoThreadFromSessionProject/)
  assert.match(desktopSource, /to: '\/\$workspaceSlug\/studio\/\$videoSessionId'/)
})
