import assert from 'node:assert/strict'
import test from 'node:test'
import { readFile } from 'node:fs/promises'

const pageSourceUrl = new URL('./video-tool-page.tsx', import.meta.url)
const routerSourceUrl = new URL('../../../../app/router.tsx', import.meta.url)
const desktopPageSourceUrl = new URL('../../layout/desktop-app-page.tsx', import.meta.url)

test('Video Studio fills the app surface without an inset page wrapper', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')

  assert.match(source, /<div className="absolute inset-0 flex min-h-0 flex-col overflow-hidden/)
  assert.match(source, /<main className="flex min-h-0 flex-1 flex-col overflow-y-auto overscroll-contain lg:flex-row lg:overflow-hidden">/)
  assert.match(source, /lg:hidden/)
  assert.doesNotMatch(source, /Coming soon for mobile/)
  assert.doesNotMatch(source, /mx-auto hidden h-full w-full max-w-none flex-col px-4 py-4/)
})

test('Video Studio tolerates legacy nullable timeline clip arrays', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  assert.match(source, /currentRevision\?\.timeline\.clips\?\.some/)
  assert.match(source, /\(currentRevision\.timeline\.clips \?\? \[\]\)\.filter/)
})

test('Video Studio reviews nested selective iterations in the sidebar and keeps the center player review-free', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const proposalSource = await readFile(new URL('../video-studio/video-studio-surface.tsx', import.meta.url), 'utf8')

  assert.match(source, /replaceCachedVideoMedia/)
  assert.match(source, /replaceCachedImageMedia/)
  assert.match(source, /<VideoIterationSidebar/)
  assert.match(source, /layoutClassName="flex max-h-\[48dvh\]/)
  assert.match(source, /childrenClassName="mt-3 min-h-0 flex-1 overflow-y-auto"/)
  assert.match(source, /compactSelectedSession=\{Boolean\(selectedThread && !selectedLibraryVideo\)\}/)
  assert.match(source, />Video workspace<\/p>/)
  assert.doesNotMatch(source, />Current movie<\/p>/)
  assert.match(source, /Previewing r\{previewRevision\.revision_number\}/)
  assert.match(source, /Restore as new version/)
  assert.match(source, /videoProjectProjectionSequence/)
  assert.match(source, /selectionKind: 'iteration'/)
  assert.match(source, /iterationContext=\{studioComposerContext\?\.iteration\}/)
  assert.match(source, /VIDEO_STUDIO_UI_PLAYHEAD_INTERVAL_MS/)
  assert.match(source, /now - lastPublishedPlayheadRef\.current >= VIDEO_STUDIO_UI_PLAYHEAD_INTERVAL_MS/)
  assert.match(source, /routeOptions=\{studioRouteOptions\}/)
  assert.match(source, /playheadMs=\{studioSidecarPlayheadMs\}/)
  assert.match(proposalSource, /memo\(function VideoIterationSidebar/)
  assert.match(proposalSource, /memo\(function VideoSessionAISidecar/)
  assert.match(source, /onMessageSent=\{handleStudioMessageSent\}/)
  assert.match(source, /aria-label="Current video turn"/)
  assert.match(source, /What changed in this turn/)
  assert.match(source, /currentWorkingVisualLayout\.map/)
  assert.match(source, /render-ready image fallbacks/)
  assert.match(source, /Still image proposed/)
  assert.match(source, /Video clip locked in/)
  assert.match(source, /Play clip \+ soundtrack/)
  assert.match(source, /Preview at this clip’s soundtrack position/)
  assert.match(source, /Keep this variant/)
  assert.match(source, /Confirm all \$\{currentWorkingVisualLayout\.length\} clips/)
  assert.match(source, /Keep this proposed clip in the confirmed cut/)
  assert.match(source, /Finish HTML motion first/)
  assert.match(source, /Revise this turn/)
  assert.match(source, /Previous revision/)
  assert.doesNotMatch(source, /choose an iteration/)
  assert.doesNotMatch(source, /Choose and attach to Swarm/)
  assert.doesNotMatch(proposalSource, /activityKeyRef/)
  assert.doesNotMatch(proposalSource, /renderedMessages\.liveRuns\.map\(\(run\)/)
  assert.doesNotMatch(source, /onActivity=\{handleStudioActivity\}/)
  assert.doesNotMatch(source, /<VideoProposalReview/)
  assert.doesNotMatch(source, /aria-label="Kept video plan"/)

  assert.match(proposalSource, /aria-label="Video iterations"/)
  assert.match(proposalSource, /buildVideoIterationTimeline/)
  assert.match(proposalSource, /setPreviewId\(newestPendingIterationId\)/)
  assert.match(proposalSource, /proposal\.accepted_operation_ids/)
  assert.match(proposalSource, /Enable \$\{change\.label\}/)
  assert.match(proposalSource, /props\.onFocusChange\(change\.clipId, change\.startMs\)/)
  assert.match(proposalSource, /Attach \$\{change\.label\} to AI composer/)
  assert.match(proposalSource, /Confirm enabled changes/)
  assert.match(proposalSource, /selectedOperationIds: enabledIds/)
  assert.match(proposalSource, /video_iteration_parent_revision_id/)
  assert.match(proposalSource, /video_iteration_candidate_revision_id/)
  assert.match(proposalSource, /video_iteration_change_id/)
  assert.match(proposalSource, /video_iteration_range_start_ms/)
  assert.match(proposalSource, /video_iteration_range_end_ms/)
})

test('Video Studio pins one clip-owned animation selection surface and an identity-led active 16:9 player', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')

  assert.match(source, /className="relative aspect-video w-full max-w-full overflow-hidden" style=\{\{ maxHeight: '100%' \}\}/)
  assert.match(source, /data-video-studio-live-animation/)
  assert.match(source, /title=\{liveAnimationCandidate\?\.label \|\| liveAnimationPart\.title\}/)
  assert.match(source, /iterationCardURLs\[`\$\{part\?\.id\}:\$\{candidate\.id\}`\]/)
  assert.match(source, /This variant does not belong to \$\{part\.title\}\./)
  assert.match(source, /HTML selected · MP4 export required/)
  assert.match(source, /Choose one HTML motion variant/)
  assert.match(source, /Motion derivative ready/)

  const selectionCalls = source.match(/selectLiveAnimationCandidate\(part, candidate\)/g) ?? []
  assert.equal(selectionCalls.length, 1, 'candidate persistence must have one clip-card control; preview and source navigation must not duplicate selection')
  assert.doesNotMatch(source, /animation sources`}>[\s\S]*selectLiveAnimationCandidate\(planPart, candidate\)/)
})

test('Video Studio exposes only the implemented soundtrack contract and an explicit audio lane', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  const proposalSource = await readFile(new URL('../video-studio/video-studio-surface.tsx', import.meta.url), 'utf8')

  assert.match(source, /aria-label="Soundtrack controls"/)
  assert.match(source, /aria-label="Soundtrack lane"/)
  assert.match(source, /aria-label="Choose trusted soundtrack"/)
  assert.match(source, /Playing pending working audio/)
  assert.match(source, /No soundtrack in this player revision/)
  assert.doesNotMatch(source, /workingSoundtrack\?\.name/)
  assert.match(source, /source_kind: 'source_audio'/)
  assert.match(source, /Propose placement \/ trim \/ volume change/)
  assert.match(proposalSource, /'replace_clip'/)
  assert.doesNotMatch(source, /Waveform|Fade in|Fade out|Loop soundtrack|Duck narration|Beat sync/)
})

test('Video Studio keeps sessions and standalone retained videos as separate navigation surfaces', async () => {
  const source = await readFile(pageSourceUrl, 'utf8')
  assert.match(source, /const videoLibraryNavigation = \([\s\S]*aria-label="Standalone video library"/)
  assert.match(source, /placeholder="Filter videos or related sessions"/)
  assert.match(source, /aria-label="Selected library video"/)
  assert.match(source, /aria-label="Selected video iteration"/)
  assert.match(source, /Videos in this session/)
  assert.match(source, /sessionsLabel="Video sessions"[\s\S]*beforeSessions=\{videoLibraryNavigation\}/)
  assert.match(source, /Start new session with r\{selectedLibraryRevision\?\.revision_number \?\? 0\} attached/)
  assert.match(source, /attachToSession: true/)
  assert.match(source, /fetchWorkspaceVideoCatalog\(selectedWorkspacePath\)/)
  assert.match(source, /Start new session with r\{selectedLibraryRevision\?\.revision_number \?\? 0\} attached/)
  assert.match(source, /source_video_revision_id/)
  assert.match(source, /source_archived/)
  assert.doesNotMatch(source, /sessionsLabel="Videos"/)
})

test('Video Studio keeps a route-backed video selection and exposes session mode', async () => {
  const [source, routerSource, desktopSource] = await Promise.all([
    readFile(pageSourceUrl, 'utf8'),
    readFile(routerSourceUrl, 'utf8'),
    readFile(desktopPageSourceUrl, 'utf8'),
  ])

  assert.match(routerSource, /path: '\/\$workspaceSlug\/studio\/\$videoSessionId'/)
  assert.match(source, /VIDEO_STUDIO_LAST_SESSION_STORAGE_KEY/)
  assert.match(source, /to: '\/\$workspaceSlug\/studio\/\$videoSessionId'/)
  assert.match(source, /to: '\/\$workspaceSlug\/\$sessionId'/)
  assert.match(source, /label: 'Open session mode'/)
  assert.match(source, /data-testid="video-studio-session-toggle"/)
  assert.match(source, /aria-label="Switch to session mode"/)
  assert.match(desktopSource, />Video sessions</)
  assert.match(desktopSource, /childLabel=""/)
  assert.match(desktopSource, /selectionGroup="video"/)
  assert.match(desktopSource, /archiveDesktopV3Sessions\(ids\)/)
  assert.doesNotMatch(desktopSource, /routeSessionIsVideoStudio \|\| videoStudioRoute/)
  assert.match(desktopSource, /routeSessionHasVideoProject = routeSessionIsVideoStudio \|\| routeSessionVideoProjectQuery\.data === true/)
  assert.match(desktopSource, /sessionVideoProjectPresenceKey\(routeSessionId, routeSessionVideoProjectSequence\)/)
  assert.match(desktopSource, /studioMode=\{routeSessionHasVideoProject \? 'session' : null\}/)
  assert.match(source, /videoThreadFromSessionProject/)
  assert.match(desktopSource, /to: '\/\$workspaceSlug\/studio\/\$videoSessionId'/)
})
