// Code generated by scripts/generate-session-connection-contract.mjs from contracts/session-connection.v1.schema.json; DO NOT EDIT.

export const SESSION_CONNECTION_CONTRACT_VERSION = 1 as const
export const SESSION_CONNECTION_PROTOCOL = 'swarm.session-stream.v1' as const
export const SESSION_CONNECTION_DEFAULT_READY_TIMEOUT_MS = 10000 as const

export type RunPhase = "accepted" | "pending_executor" | "executor_started" | "provider_request_started" | "provider_first_event" | "output_streaming" | "waiting_permission" | "completed" | "failed" | "cancelled" | "interrupted"

export interface SessionErrorAction {
  method: string
  path: string
}

export interface SessionConnectionError {
  code: string
  message: string
  retryable: boolean
  action: SessionErrorAction
}

export interface SessionConnectRequest {
  client_id: string
  request_id: string
  resume_token: string | null
}

export interface RunPhaseReason {
  code: string
  message: string
  retryable?: boolean
}

export interface SessionCurrentRun {
  run_id: string
  phase: RunPhase
  reason?: RunPhaseReason | null
}

export interface SessionSnapshot {
  event_seq: number
  session: unknown
  messages: unknown[]
  current_run: SessionCurrentRun | null
  pending_permissions: unknown[]
  active_plan: unknown | null
  usage: unknown | null
}

export interface SessionConnectionInfo {
  connection_id: string
  transport: "websocket"
  protocol: "swarm.session-stream.v1"
  stream_url: string
  resume_token: string
  ready_timeout_ms: number
}

export interface SessionConnectResponse {
  ok: true
  contract_version: 1
  session_id: string
  snapshot: SessionSnapshot
  connection: SessionConnectionInfo
}

export interface SessionReadyFrame {
  type: "session.ready"
  connection_id: string
  session_id: string
  event_seq: number
  resume_token: string
}

export interface SessionEventFrame {
  type: "session.event"
  session_id: string
  event_seq: number
  event: unknown
  resume_token: string
}

export interface RunPhaseFrame {
  type: "run.phase"
  session_id: string
  run_id: string
  phase: RunPhase
  event_seq: number
  reason?: RunPhaseReason | null
}

export type SessionReconnectRequiredReason = "resume_token_expired" | "connection_lease_lost" | "session_deleted" | "authorization_lost" | "slow_consumer"

export interface SessionReconnectRequiredFrame {
  type: "session.reconnect_required"
  session_id: string
  reason: "resume_token_expired" | "connection_lease_lost" | "session_deleted" | "authorization_lost" | "slow_consumer"
  action: SessionErrorAction
}

export type SessionStreamFrame = SessionReadyFrame | SessionEventFrame | RunPhaseFrame | SessionReconnectRequiredFrame
