/**
 * Generates latency-optimized multi-stage Dockerfiles and container configurations for Swarm.
 */

import type { BuildStrategy, SourceConfig } from './types.js';

export interface DockerfileOptions {
  /** Source configuration */
  source?: SourceConfig;
  /** Listen port (default: 18080) */
  port?: number;
  /** Build strategy */
  strategy?: BuildStrategy;
  /** Go compiler version tag */
  goVersion?: string;
  /** Binary subpath in repo (default: './cmd/swarmd') */
  packagePath?: string;
}

/**
 * Generates an optimal multi-stage Dockerfile tailored for low latency and fast image pulls.
 *
 * Optimizations applied:
 * 1. Multi-stage build discarding all build tools and source files.
 * 2. CGO_ENABLED=0 with -ldflags="-s -w" stripping DWARF tables and symbol tables.
 * 3. Minimal distroless static runtime (gcr.io/distroless/static-debian12:nonroot), dropping size from ~450MB to <35MB.
 * 4. Zero binary compression (UPX omitted because decompression adds ~1s CPU startup latency on cold boots).
 * 5. Non-root user execution for security compliance.
 */
export function generateOptimizedDockerfile(options: DockerfileOptions = {}): string {
  const strategy = options.strategy || options.source?.buildStrategy || 'distroless';
  const port = options.port ?? 18080;
  const goVersion = options.goVersion || '1.24-bookworm';
  const pkgPath = options.packagePath || './cmd/swarmd';
  const source = options.source;

  if (source?.type === 'binary' && source.binaryUrl) {
    // Binary download mode: fetch precompiled binary and place in minimal container
    const runtimeBase = getRuntimeBaseImage(strategy);
    return `# Swarm Minimal Container (Precompiled Binary)
# Generated by @swarm/sdk deploy module

FROM alpine:3.21 AS fetcher
RUN apk add --no-cache curl ca-certificates
WORKDIR /workspace
RUN curl -fsSL "${source.binaryUrl}" -o /workspace/swarmd && chmod +x /workspace/swarmd

FROM ${runtimeBase}
COPY --from=fetcher /workspace/swarmd /bin/swarmd
EXPOSE ${port}
ENV PORT=${port}
USER 65532:65532
ENTRYPOINT ["/bin/swarmd"]
`;
  }

  if (source?.type === 'github') {
    const repoUrl = source.repository || 'https://github.com/swarm-agent/swarm';
    const branch = source.branch || 'main';
    const checkoutCmd = source.commit
      ? `git clone --depth 1 "${repoUrl}" /src && cd /src && git checkout "${source.commit}"`
      : `git clone --depth 1 --branch "${branch}" "${repoUrl}" /src`;

    const runtimeBase = getRuntimeBaseImage(strategy);

    return `# Swarm Multi-Stage Container (GitHub Source Clone)
# Generated by @swarm/sdk deploy module
# Repository: ${repoUrl} (branch: ${branch})

# Stage 1: Build binary with stripped debug symbols (-s -w)
FROM golang:${goVersion} AS builder
RUN apt-get update && apt-get install -y --no-install-recommends git ca-certificates && rm -rf /var/lib/apt/lists/*
WORKDIR /src
RUN ${checkoutCmd}
RUN go mod download
# Stripped static Go binary: zero CGO, no debug symbols, maximum cold-start speed
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /bin/swarmd ${pkgPath}

# Stage 2: Runtime image (<35MB total container size)
FROM ${runtimeBase}
COPY --from=builder /bin/swarmd /bin/swarmd
EXPOSE ${port}
ENV PORT=${port}
USER 65532:65532
ENTRYPOINT ["/bin/swarmd"]
`;
  }

  // Local directory source build (standard workspace container build)
  const runtimeBase = getRuntimeBaseImage(strategy);

  return `# Swarm Multi-Stage Container (Local Source Context)
# Generated by @swarm/sdk deploy module

# Stage 1: Builder
FROM golang:${goVersion} AS builder
WORKDIR /src

# Leverage Docker layer caching for modules
COPY go.mod go.sum* ./
RUN if [ -f go.mod ]; then go mod download; fi

# Copy source tree and compile stripped static binary
COPY . .
RUN CGO_ENABLED=0 GOOS=linux go build -trimpath -ldflags="-s -w" -o /bin/swarmd ${pkgPath}

# Stage 2: Ultra-lean runtime (<35MB)
FROM ${runtimeBase}
COPY --from=builder /bin/swarmd /bin/swarmd
EXPOSE ${port}
ENV PORT=${port}
USER 65532:65532
ENTRYPOINT ["/bin/swarmd"]
`;
}

function getRuntimeBaseImage(strategy: BuildStrategy): string {
  switch (strategy) {
    case 'distroless':
      return 'gcr.io/distroless/static-debian12:nonroot';
    case 'scratch':
      return 'scratch';
    case 'alpine':
      return 'alpine:3.21';
    default:
      return 'gcr.io/distroless/static-debian12:nonroot';
  }
}

/**
 * Generates an optimal .dockerignore file preventing unneeded files from inflating build context.
 */
export function generateDockerIgnore(): string {
  return `# Generated by @swarm/sdk deploy module
.git
.github
node_modules
web/node_modules
packages/*/node_modules
dist
packages/*/dist
*.log
*.tmp
.env
.env.*
*.sock
tmp
.vscode
.idea
`;
}
