minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - esbuild
  - '@esbuild/*'
blockExoticSubdeps: true
overrides:
  postcss: 8.5.23
allowBuilds:
  esbuild: true
  fsevents: true
  node: true
