minimumReleaseAge: 10080
minimumReleaseAgeStrict: true
minimumReleaseAgeIgnoreMissingTime: false
minimumReleaseAgeExclude:
  - esbuild
  - '@esbuild/*'
blockExoticSubdeps: true
allowBuilds:
  esbuild: true
  fsevents: true
  node: true
